kind = "Project"
name = "button"

[nodes.output]
def = { path = "./output.toml" }

[nodes.button]
def = { path = "./button.toml" }

[nodes.shader]
def = { path = "./shader.toml" }

[nodes.fixture]
def = { path = "./fixture.toml" }
