kind = "Shader"
source = { path = "shader.glsl" }
render_order = 0

[bindings.output]
target = "bus#visual.out"

[bindings.held]
source = "bus#trigger"

[glsl_opts]
add_sub = "wrapping"
mul = "wrapping"
div = "reciprocal"

[consumed.held]
kind = "map"
key = "u32"
value = "lp::control::Message"
mapping = { kind = "sentinel", len = 1, key = "id", empty_key = 0 }
