//! wasmtime host dispatch into `lps-builtins` (guest linear memory for pointer ABI).
//!
//! AUTO-GENERATED by lps-builtins-gen-app. Do not edit manually.
//!
//! Regenerate: `cargo run -p lps-builtins-gen-app` or `scripts/build-builtins.sh`

use wasmtime::{Caller, Memory, Val};

use lps_builtin_ids::BuiltinId;

/// Linear memory handle supplied at link time (`env.memory` from [`super::link`]).
///
/// `Caller::get_export` only sees WASM **exports**; our shaders **import** `env.memory`, so there is
/// no `"env"` export to discover. Always use the memory handle wired into the linker.
pub(super) fn dispatch_native_builtin(
    mut caller: Caller<'_, ()>,
    linked_env_memory: Memory,
    id: BuiltinId,
    params: &[Val],
    results: &mut [Val],
) -> Result<(), wasmtime::Error> {
    match id {
        BuiltinId::LpGlslAcosQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::acos_q32::__lps_acos_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslAcoshQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::acosh_q32::__lps_acosh_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslAsinQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::asin_q32::__lps_asin_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslAsinhQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::asinh_q32::__lps_asinh_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslAtan2Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let r = lps_builtins::builtins::glsl::atan2_q32::__lps_atan2_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslAtanQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::atan_q32::__lps_atan_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslAtanhQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::atanh_q32::__lps_atanh_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslCosQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::cos_q32::__lps_cos_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslCoshQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::cosh_q32::__lps_cosh_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslExp2Q32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::exp2_q32::__lps_exp2_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslExpQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::exp_q32::__lps_exp_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslFmaQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let r = lps_builtins::builtins::glsl::fma_q32::__lps_fma_q32(p0, p1, p2);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslInversesqrtQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::inversesqrt_q32::__lps_inversesqrt_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslLdexpQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let r = lps_builtins::builtins::glsl::ldexp_q32::__lps_ldexp_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslLog2Q32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::log2_q32::__lps_log2_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslLogQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::log_q32::__lps_log_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslModQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let r = lps_builtins::builtins::glsl::mod_q32::__lps_mod_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslPowQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let r = lps_builtins::builtins::glsl::pow_q32::__lps_pow_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslRoundQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::round_q32::__lps_round_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslSinQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::sin_q32::__lps_sin_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslSinhQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::sinh_q32::__lps_sinh_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslTanQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::tan_q32::__lps_tan_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslTanhQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::tanh_q32::__lps_tanh_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnFbm2F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::fbm::fbm2_f32::__lp_lpfn_fbm2_f32(
                p0, p1, p2, p3,
            );
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnFbm2Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::fbm::fbm2_q32::__lp_lpfn_fbm2_q32(
                p0, p1, p2, p3,
            );
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnFbm3F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::fbm::fbm3_f32::__lp_lpfn_fbm3_f32(
                p0, p1, p2, p3, p4,
            );
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnFbm3Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::fbm::fbm3_q32::__lp_lpfn_fbm3_q32(
                p0, p1, p2, p3, p4,
            );
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnFbm3TileF32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            let p4 = params[4].unwrap_i32();
            let p5 = params[5].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::fbm::fbm3_tile_f32::__lp_lpfn_fbm3_tile_f32(p0, p1, p2, p3, p4, p5);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnFbm3TileQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32();
            let p5 = params[5].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::fbm::fbm3_tile_q32::__lp_lpfn_fbm3_tile_q32(p0, p1, p2, p3, p4, p5);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnGnoise1F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::gnoise::gnoise1_f32::__lp_lpfn_gnoise1_f32(p0, p1);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnGnoise1Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::gnoise::gnoise1_q32::__lp_lpfn_gnoise1_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnGnoise2F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::gnoise::gnoise2_f32::__lp_lpfn_gnoise2_f32(p0, p1, p2);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnGnoise2Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::gnoise::gnoise2_q32::__lp_lpfn_gnoise2_q32(p0, p1, p2);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnGnoise3F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::gnoise::gnoise3_f32::__lp_lpfn_gnoise3_f32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnGnoise3Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::gnoise::gnoise3_q32::__lp_lpfn_gnoise3_q32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnGnoise3TileF32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            let p4 = params[4].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::gnoise::gnoise3_tile_f32::__lp_lpfn_gnoise3_tile_f32(p0, p1, p2, p3, p4);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnGnoise3TileQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::gnoise::gnoise3_tile_q32::__lp_lpfn_gnoise3_tile_q32(p0, p1, p2, p3, p4);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnHash1 => {
            let p0 = params[0].unwrap_i32() as u32;
            let p1 = params[1].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::hash::__lp_lpfn_hash_1(p0, p1);
            results[0] = wasmtime::Val::I32(r as i32);
            Ok(())
        }
        BuiltinId::LpLpfnHash2 => {
            let p0 = params[0].unwrap_i32() as u32;
            let p1 = params[1].unwrap_i32() as u32;
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::hash::__lp_lpfn_hash_2(p0, p1, p2);
            results[0] = wasmtime::Val::I32(r as i32);
            Ok(())
        }
        BuiltinId::LpLpfnHash3 => {
            let p0 = params[0].unwrap_i32() as u32;
            let p1 = params[1].unwrap_i32() as u32;
            let p2 = params[2].unwrap_i32() as u32;
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::hash::__lp_lpfn_hash_3(p0, p1, p2, p3);
            results[0] = wasmtime::Val::I32(r as i32);
            Ok(())
        }
        BuiltinId::LpLpfnHsv2rgbF32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0f32; 3];
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            lps_builtins::builtins::lpfn::color::space::hsv2rgb_f32::__lp_lpfn_hsv2rgb_f32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnHsv2rgbQ32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0i32; 3];
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            lps_builtins::builtins::lpfn::color::space::hsv2rgb_q32::__lp_lpfn_hsv2rgb_q32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnHsv2rgbVec4F32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0f32; 4];
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            let p4 = params[4].unwrap_f32();
            lps_builtins::builtins::lpfn::color::space::hsv2rgb_f32::__lp_lpfn_hsv2rgb_vec4_f32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
                p4,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnHsv2rgbVec4Q32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0i32; 4];
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32();
            lps_builtins::builtins::lpfn::color::space::hsv2rgb_q32::__lp_lpfn_hsv2rgb_vec4_q32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
                p4,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnHue2rgbF32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0f32; 3];
            let p1 = params[1].unwrap_f32();
            lps_builtins::builtins::lpfn::color::space::hue2rgb_f32::__lp_lpfn_hue2rgb_f32(
                buf_0.as_mut_ptr(),
                p1,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnHue2rgbQ32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0i32; 3];
            let p1 = params[1].unwrap_i32();
            lps_builtins::builtins::lpfn::color::space::hue2rgb_q32::__lp_lpfn_hue2rgb_q32(
                buf_0.as_mut_ptr(),
                p1,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnPsrdnoise2F32 => {
            let mem = linked_env_memory;
            let off_5 = params[5].unwrap_i32() as u32 as usize;
            let mut buf_5 = [0f32; 2];
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            let p4 = params[4].unwrap_f32();
            let p6 = params[6].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::psrdnoise::psrdnoise2_f32::__lp_lpfn_psrdnoise2_f32(p0, p1, p2, p3, p4, buf_5.as_mut_ptr(), p6);
            results[0] = wasmtime::Val::F32(r.to_bits());
            for (i, v) in buf_5.iter().enumerate() {
                mem.write(&mut caller, off_5 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnPsrdnoise2Q32 => {
            let mem = linked_env_memory;
            let off_5 = params[5].unwrap_i32() as u32 as usize;
            let mut buf_5 = [0i32; 2];
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32();
            let p6 = params[6].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::psrdnoise::psrdnoise2_q32::__lp_lpfn_psrdnoise2_q32(p0, p1, p2, p3, p4, buf_5.as_mut_ptr(), p6);
            results[0] = wasmtime::Val::I32(r);
            for (i, v) in buf_5.iter().enumerate() {
                mem.write(&mut caller, off_5 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnPsrdnoise3F32 => {
            let mem = linked_env_memory;
            let off_7 = params[7].unwrap_i32() as u32 as usize;
            let mut buf_7 = [0f32; 3];
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            let p4 = params[4].unwrap_f32();
            let p5 = params[5].unwrap_f32();
            let p6 = params[6].unwrap_f32();
            let p8 = params[8].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::psrdnoise::psrdnoise3_f32::__lp_lpfn_psrdnoise3_f32(p0, p1, p2, p3, p4, p5, p6, buf_7.as_mut_ptr(), p8);
            results[0] = wasmtime::Val::F32(r.to_bits());
            for (i, v) in buf_7.iter().enumerate() {
                mem.write(&mut caller, off_7 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnPsrdnoise3Q32 => {
            let mem = linked_env_memory;
            let off_7 = params[7].unwrap_i32() as u32 as usize;
            let mut buf_7 = [0i32; 3];
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32();
            let p5 = params[5].unwrap_i32();
            let p6 = params[6].unwrap_i32();
            let p8 = params[8].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::psrdnoise::psrdnoise3_q32::__lp_lpfn_psrdnoise3_q32(p0, p1, p2, p3, p4, p5, p6, buf_7.as_mut_ptr(), p8);
            results[0] = wasmtime::Val::I32(r);
            for (i, v) in buf_7.iter().enumerate() {
                mem.write(&mut caller, off_7 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnRandom1F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::random::random1_f32::__lp_lpfn_random1_f32(p0, p1);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnRandom1Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::random::random1_q32::__lp_lpfn_random1_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnRandom2F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::random::random2_f32::__lp_lpfn_random2_f32(p0, p1, p2);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnRandom2Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::random::random2_q32::__lp_lpfn_random2_q32(p0, p1, p2);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnRandom3F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::random::random3_f32::__lp_lpfn_random3_f32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnRandom3Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::random::random3_q32::__lp_lpfn_random3_q32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnRgb2hsvF32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0f32; 3];
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            lps_builtins::builtins::lpfn::color::space::rgb2hsv_f32::__lp_lpfn_rgb2hsv_f32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnRgb2hsvQ32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0i32; 3];
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            lps_builtins::builtins::lpfn::color::space::rgb2hsv_q32::__lp_lpfn_rgb2hsv_q32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnRgb2hsvVec4F32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0f32; 4];
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            let p4 = params[4].unwrap_f32();
            lps_builtins::builtins::lpfn::color::space::rgb2hsv_f32::__lp_lpfn_rgb2hsv_vec4_f32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
                p4,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnRgb2hsvVec4Q32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0i32; 4];
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32();
            lps_builtins::builtins::lpfn::color::space::rgb2hsv_q32::__lp_lpfn_rgb2hsv_vec4_q32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
                p4,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnSaturateF32 => {
            let p0 = params[0].unwrap_f32();
            let r = lps_builtins::builtins::lpfn::math::saturate_f32::__lp_lpfn_saturate_f32(p0);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnSaturateQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpfn::math::saturate_q32::__lp_lpfn_saturate_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnSaturateVec3F32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0f32; 3];
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            lps_builtins::builtins::lpfn::math::saturate_f32::__lp_lpfn_saturate_vec3_f32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnSaturateVec3Q32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0i32; 3];
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            lps_builtins::builtins::lpfn::math::saturate_q32::__lp_lpfn_saturate_vec3_q32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnSaturateVec4F32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0f32; 4];
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            let p4 = params[4].unwrap_f32();
            lps_builtins::builtins::lpfn::math::saturate_f32::__lp_lpfn_saturate_vec4_f32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
                p4,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnSaturateVec4Q32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0i32; 4];
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32();
            lps_builtins::builtins::lpfn::math::saturate_q32::__lp_lpfn_saturate_vec4_q32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
                p4,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnSnoise1F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::snoise::snoise1_f32::__lp_lpfn_snoise1_f32(p0, p1);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnSnoise1Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::snoise::snoise1_q32::__lp_lpfn_snoise1_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnSnoise2F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::snoise::snoise2_f32::__lp_lpfn_snoise2_f32(p0, p1, p2);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnSnoise2Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::snoise::snoise2_q32::__lp_lpfn_snoise2_q32(p0, p1, p2);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnSnoise3F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::snoise::snoise3_f32::__lp_lpfn_snoise3_f32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnSnoise3Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::snoise::snoise3_q32::__lp_lpfn_snoise3_q32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnSrandom1F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::srandom::srandom1_f32::__lp_lpfn_srandom1_f32(p0, p1);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnSrandom1Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::srandom::srandom1_q32::__lp_lpfn_srandom1_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnSrandom2F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::srandom::srandom2_f32::__lp_lpfn_srandom2_f32(p0, p1, p2);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnSrandom2Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::srandom::srandom2_q32::__lp_lpfn_srandom2_q32(p0, p1, p2);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnSrandom3F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::srandom::srandom3_f32::__lp_lpfn_srandom3_f32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnSrandom3Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::srandom::srandom3_q32::__lp_lpfn_srandom3_q32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnSrandom3TileF32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0f32; 3];
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            let p4 = params[4].unwrap_f32();
            let p5 = params[5].unwrap_i32() as u32;
            lps_builtins::builtins::lpfn::generative::srandom::srandom3_tile_f32::__lp_lpfn_srandom3_tile_f32(buf_0.as_mut_ptr(), p1, p2, p3, p4, p5);
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnSrandom3TileQ32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0i32; 3];
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32();
            let p5 = params[5].unwrap_i32() as u32;
            lps_builtins::builtins::lpfn::generative::srandom::srandom3_tile_q32::__lp_lpfn_srandom3_tile_q32(buf_0.as_mut_ptr(), p1, p2, p3, p4, p5);
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnSrandom3VecF32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0f32; 3];
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            let p4 = params[4].unwrap_i32() as u32;
            lps_builtins::builtins::lpfn::generative::srandom::srandom3_vec_f32::__lp_lpfn_srandom3_vec_f32(buf_0.as_mut_ptr(), p1, p2, p3, p4);
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnSrandom3VecQ32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0i32; 3];
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32() as u32;
            lps_builtins::builtins::lpfn::generative::srandom::srandom3_vec_q32::__lp_lpfn_srandom3_vec_q32(buf_0.as_mut_ptr(), p1, p2, p3, p4);
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfnWorley2F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::worley::worley2_f32::__lp_lpfn_worley2_f32(p0, p1, p2);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnWorley2Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::worley::worley2_q32::__lp_lpfn_worley2_q32(p0, p1, p2);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnWorley2ValueF32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::worley::worley2_value_f32::__lp_lpfn_worley2_value_f32(p0, p1, p2);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnWorley2ValueQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::worley::worley2_value_q32::__lp_lpfn_worley2_value_q32(p0, p1, p2);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnWorley3F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::worley::worley3_f32::__lp_lpfn_worley3_f32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnWorley3Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::worley::worley3_q32::__lp_lpfn_worley3_q32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfnWorley3ValueF32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::worley::worley3_value_f32::__lp_lpfn_worley3_value_f32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfnWorley3ValueQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfn::generative::worley::worley3_value_q32::__lp_lpfn_worley3_value_q32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFabsQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpir::float_misc_q32::__lp_lpir_fabs_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFaddQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let r = lps_builtins::builtins::lpir::fadd_q32::__lp_lpir_fadd_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFceilQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpir::float_misc_q32::__lp_lpir_fceil_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFdivQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let r = lps_builtins::builtins::lpir::fdiv_q32::__lp_lpir_fdiv_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFfloorQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpir::float_misc_q32::__lp_lpir_ffloor_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFmaxQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let r = lps_builtins::builtins::lpir::float_misc_q32::__lp_lpir_fmax_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFminQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let r = lps_builtins::builtins::lpir::float_misc_q32::__lp_lpir_fmin_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFmulQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let r = lps_builtins::builtins::lpir::fmul_q32::__lp_lpir_fmul_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFnearestQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpir::fnearest_q32::__lp_lpir_fnearest_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFsqrtQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpir::fsqrt_q32::__lp_lpir_fsqrt_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFsubQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let r = lps_builtins::builtins::lpir::fsub_q32::__lp_lpir_fsub_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFtoUnorm16Q32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpir::unorm_conv_q32::__lp_lpir_fto_unorm16_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFtoUnorm8Q32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpir::unorm_conv_q32::__lp_lpir_fto_unorm8_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFtoiSatSQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpir::ftoi_sat_q32::__lp_lpir_ftoi_sat_s_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFtoiSatUQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpir::ftoi_sat_q32::__lp_lpir_ftoi_sat_u_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFtruncQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpir::float_misc_q32::__lp_lpir_ftrunc_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirItofSQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpir::itof_s_q32::__lp_lpir_itof_s_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirItofUQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpir::itof_u_q32::__lp_lpir_itof_u_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirUnorm16ToFQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpir::unorm_conv_q32::__lp_lpir_unorm16_to_f_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirUnorm8ToFQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpir::unorm_conv_q32::__lp_lpir_unorm8_to_f_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpVmGetFuelQ32 => {
            let vmctx_word = params[0].unwrap_i32();
            let mem = linked_env_memory;
            let base = vmctx_word as u32 as usize;
            let mut buf = [0u8; 8];
            mem.read(&caller, base, &mut buf)
                .map_err(|e| wasmtime::Error::msg(format!("vmctx fuel read: {e}")))?;
            let fuel = u64::from_le_bytes(buf);
            results[0] = wasmtime::Val::I32(fuel as u32 as i32);
            Ok(())
        }
    }
}
