//! wasmtime host dispatch into `lps-builtins` (guest linear memory for pointer ABI).
//!
//! AUTO-GENERATED by lps-builtins-gen-app. Do not edit manually.
//!
//! Regenerate: `cargo run -p lps-builtins-gen-app` or `scripts/build-builtins.sh`

use wasmtime::{Caller, Memory, Val};

use lps_builtin_ids::BuiltinId;

/// Linear memory handle supplied at link time (`env.memory` from [`super::link`]).
///
/// `Caller::get_export` only sees WASM **exports**; our shaders **import** `env.memory`, so there is
/// no `"env"` export to discover. Always use the memory handle wired into the linker.
pub(super) fn dispatch_native_builtin(
    mut caller: Caller<'_, ()>,
    linked_env_memory: Memory,
    id: BuiltinId,
    params: &[Val],
    results: &mut [Val],
) -> Result<(), wasmtime::Error> {
    match id {
        BuiltinId::LpGlslAcosQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::acos_q32::__lps_acos_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslAcoshQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::acosh_q32::__lps_acosh_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslAsinQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::asin_q32::__lps_asin_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslAsinhQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::asinh_q32::__lps_asinh_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslAtan2Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let r = lps_builtins::builtins::glsl::atan2_q32::__lps_atan2_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslAtanQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::atan_q32::__lps_atan_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslAtanhQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::atanh_q32::__lps_atanh_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslCosQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::cos_q32::__lps_cos_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslCoshQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::cosh_q32::__lps_cosh_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslExp2Q32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::exp2_q32::__lps_exp2_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslExpQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::exp_q32::__lps_exp_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslFmaQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let r = lps_builtins::builtins::glsl::fma_q32::__lps_fma_q32(p0, p1, p2);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslInversesqrtQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::inversesqrt_q32::__lps_inversesqrt_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslLdexpQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let r = lps_builtins::builtins::glsl::ldexp_q32::__lps_ldexp_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslLog2Q32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::log2_q32::__lps_log2_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslLogQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::log_q32::__lps_log_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslModQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let r = lps_builtins::builtins::glsl::mod_q32::__lps_mod_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslPowQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let r = lps_builtins::builtins::glsl::pow_q32::__lps_pow_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslRoundQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::round_q32::__lps_round_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslSinQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::sin_q32::__lps_sin_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslSinhQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::sinh_q32::__lps_sinh_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslTanQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::tan_q32::__lps_tan_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpGlslTanhQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::glsl::tanh_q32::__lps_tanh_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxFbm2F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::fbm::fbm2_f32::__lp_lpfx_fbm2_f32(
                p0, p1, p2, p3,
            );
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxFbm2Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::fbm::fbm2_q32::__lp_lpfx_fbm2_q32(
                p0, p1, p2, p3,
            );
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxFbm3F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::fbm::fbm3_f32::__lp_lpfx_fbm3_f32(
                p0, p1, p2, p3, p4,
            );
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxFbm3Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::fbm::fbm3_q32::__lp_lpfx_fbm3_q32(
                p0, p1, p2, p3, p4,
            );
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxFbm3TileF32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            let p4 = params[4].unwrap_i32();
            let p5 = params[5].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::fbm::fbm3_tile_f32::__lp_lpfx_fbm3_tile_f32(p0, p1, p2, p3, p4, p5);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxFbm3TileQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32();
            let p5 = params[5].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::fbm::fbm3_tile_q32::__lp_lpfx_fbm3_tile_q32(p0, p1, p2, p3, p4, p5);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxGnoise1F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::gnoise::gnoise1_f32::__lp_lpfx_gnoise1_f32(p0, p1);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxGnoise1Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::gnoise::gnoise1_q32::__lp_lpfx_gnoise1_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxGnoise2F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::gnoise::gnoise2_f32::__lp_lpfx_gnoise2_f32(p0, p1, p2);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxGnoise2Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::gnoise::gnoise2_q32::__lp_lpfx_gnoise2_q32(p0, p1, p2);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxGnoise3F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::gnoise::gnoise3_f32::__lp_lpfx_gnoise3_f32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxGnoise3Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::gnoise::gnoise3_q32::__lp_lpfx_gnoise3_q32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxGnoise3TileF32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            let p4 = params[4].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::gnoise::gnoise3_tile_f32::__lp_lpfx_gnoise3_tile_f32(p0, p1, p2, p3, p4);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxGnoise3TileQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::gnoise::gnoise3_tile_q32::__lp_lpfx_gnoise3_tile_q32(p0, p1, p2, p3, p4);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxHash1 => {
            let p0 = params[0].unwrap_i32() as u32;
            let p1 = params[1].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::hash::__lp_lpfx_hash_1(p0, p1);
            results[0] = wasmtime::Val::I32(r as i32);
            Ok(())
        }
        BuiltinId::LpLpfxHash2 => {
            let p0 = params[0].unwrap_i32() as u32;
            let p1 = params[1].unwrap_i32() as u32;
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::hash::__lp_lpfx_hash_2(p0, p1, p2);
            results[0] = wasmtime::Val::I32(r as i32);
            Ok(())
        }
        BuiltinId::LpLpfxHash3 => {
            let p0 = params[0].unwrap_i32() as u32;
            let p1 = params[1].unwrap_i32() as u32;
            let p2 = params[2].unwrap_i32() as u32;
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::hash::__lp_lpfx_hash_3(p0, p1, p2, p3);
            results[0] = wasmtime::Val::I32(r as i32);
            Ok(())
        }
        BuiltinId::LpLpfxHsv2rgbF32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0f32; 3];
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            lps_builtins::builtins::lpfx::color::space::hsv2rgb_f32::__lp_lpfx_hsv2rgb_f32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxHsv2rgbQ32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0i32; 3];
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            lps_builtins::builtins::lpfx::color::space::hsv2rgb_q32::__lp_lpfx_hsv2rgb_q32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxHsv2rgbVec4F32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0f32; 4];
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            let p4 = params[4].unwrap_f32();
            lps_builtins::builtins::lpfx::color::space::hsv2rgb_f32::__lp_lpfx_hsv2rgb_vec4_f32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
                p4,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxHsv2rgbVec4Q32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0i32; 4];
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32();
            lps_builtins::builtins::lpfx::color::space::hsv2rgb_q32::__lp_lpfx_hsv2rgb_vec4_q32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
                p4,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxHue2rgbF32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0f32; 3];
            let p1 = params[1].unwrap_f32();
            lps_builtins::builtins::lpfx::color::space::hue2rgb_f32::__lp_lpfx_hue2rgb_f32(
                buf_0.as_mut_ptr(),
                p1,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxHue2rgbQ32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0i32; 3];
            let p1 = params[1].unwrap_i32();
            lps_builtins::builtins::lpfx::color::space::hue2rgb_q32::__lp_lpfx_hue2rgb_q32(
                buf_0.as_mut_ptr(),
                p1,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxPsrdnoise2F32 => {
            let mem = linked_env_memory;
            let off_5 = params[5].unwrap_i32() as u32 as usize;
            let mut buf_5 = [0f32; 2];
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            let p4 = params[4].unwrap_f32();
            let p6 = params[6].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::psrdnoise::psrdnoise2_f32::__lp_lpfx_psrdnoise2_f32(p0, p1, p2, p3, p4, buf_5.as_mut_ptr(), p6);
            results[0] = wasmtime::Val::F32(r.to_bits());
            for (i, v) in buf_5.iter().enumerate() {
                mem.write(&mut caller, off_5 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxPsrdnoise2Q32 => {
            let mem = linked_env_memory;
            let off_5 = params[5].unwrap_i32() as u32 as usize;
            let mut buf_5 = [0i32; 2];
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32();
            let p6 = params[6].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::psrdnoise::psrdnoise2_q32::__lp_lpfx_psrdnoise2_q32(p0, p1, p2, p3, p4, buf_5.as_mut_ptr(), p6);
            results[0] = wasmtime::Val::I32(r);
            for (i, v) in buf_5.iter().enumerate() {
                mem.write(&mut caller, off_5 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxPsrdnoise3F32 => {
            let mem = linked_env_memory;
            let off_7 = params[7].unwrap_i32() as u32 as usize;
            let mut buf_7 = [0f32; 3];
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            let p4 = params[4].unwrap_f32();
            let p5 = params[5].unwrap_f32();
            let p6 = params[6].unwrap_f32();
            let p8 = params[8].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::psrdnoise::psrdnoise3_f32::__lp_lpfx_psrdnoise3_f32(p0, p1, p2, p3, p4, p5, p6, buf_7.as_mut_ptr(), p8);
            results[0] = wasmtime::Val::F32(r.to_bits());
            for (i, v) in buf_7.iter().enumerate() {
                mem.write(&mut caller, off_7 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxPsrdnoise3Q32 => {
            let mem = linked_env_memory;
            let off_7 = params[7].unwrap_i32() as u32 as usize;
            let mut buf_7 = [0i32; 3];
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32();
            let p5 = params[5].unwrap_i32();
            let p6 = params[6].unwrap_i32();
            let p8 = params[8].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::psrdnoise::psrdnoise3_q32::__lp_lpfx_psrdnoise3_q32(p0, p1, p2, p3, p4, p5, p6, buf_7.as_mut_ptr(), p8);
            results[0] = wasmtime::Val::I32(r);
            for (i, v) in buf_7.iter().enumerate() {
                mem.write(&mut caller, off_7 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxRandom1F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::random::random1_f32::__lp_lpfx_random1_f32(p0, p1);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxRandom1Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::random::random1_q32::__lp_lpfx_random1_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxRandom2F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::random::random2_f32::__lp_lpfx_random2_f32(p0, p1, p2);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxRandom2Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::random::random2_q32::__lp_lpfx_random2_q32(p0, p1, p2);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxRandom3F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::random::random3_f32::__lp_lpfx_random3_f32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxRandom3Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::random::random3_q32::__lp_lpfx_random3_q32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxRgb2hsvF32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0f32; 3];
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            lps_builtins::builtins::lpfx::color::space::rgb2hsv_f32::__lp_lpfx_rgb2hsv_f32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxRgb2hsvQ32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0i32; 3];
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            lps_builtins::builtins::lpfx::color::space::rgb2hsv_q32::__lp_lpfx_rgb2hsv_q32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxRgb2hsvVec4F32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0f32; 4];
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            let p4 = params[4].unwrap_f32();
            lps_builtins::builtins::lpfx::color::space::rgb2hsv_f32::__lp_lpfx_rgb2hsv_vec4_f32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
                p4,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxRgb2hsvVec4Q32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0i32; 4];
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32();
            lps_builtins::builtins::lpfx::color::space::rgb2hsv_q32::__lp_lpfx_rgb2hsv_vec4_q32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
                p4,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxSaturateF32 => {
            let p0 = params[0].unwrap_f32();
            let r = lps_builtins::builtins::lpfx::math::saturate_f32::__lp_lpfx_saturate_f32(p0);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxSaturateQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpfx::math::saturate_q32::__lp_lpfx_saturate_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxSaturateVec3F32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0f32; 3];
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            lps_builtins::builtins::lpfx::math::saturate_f32::__lp_lpfx_saturate_vec3_f32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxSaturateVec3Q32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0i32; 3];
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            lps_builtins::builtins::lpfx::math::saturate_q32::__lp_lpfx_saturate_vec3_q32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxSaturateVec4F32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0f32; 4];
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            let p4 = params[4].unwrap_f32();
            lps_builtins::builtins::lpfx::math::saturate_f32::__lp_lpfx_saturate_vec4_f32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
                p4,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxSaturateVec4Q32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0i32; 4];
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32();
            lps_builtins::builtins::lpfx::math::saturate_q32::__lp_lpfx_saturate_vec4_q32(
                buf_0.as_mut_ptr(),
                p1,
                p2,
                p3,
                p4,
            );
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxSnoise1F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::snoise::snoise1_f32::__lp_lpfx_snoise1_f32(p0, p1);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxSnoise1Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::snoise::snoise1_q32::__lp_lpfx_snoise1_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxSnoise2F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::snoise::snoise2_f32::__lp_lpfx_snoise2_f32(p0, p1, p2);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxSnoise2Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::snoise::snoise2_q32::__lp_lpfx_snoise2_q32(p0, p1, p2);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxSnoise3F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::snoise::snoise3_f32::__lp_lpfx_snoise3_f32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxSnoise3Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::snoise::snoise3_q32::__lp_lpfx_snoise3_q32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxSrandom1F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::srandom::srandom1_f32::__lp_lpfx_srandom1_f32(p0, p1);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxSrandom1Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::srandom::srandom1_q32::__lp_lpfx_srandom1_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxSrandom2F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::srandom::srandom2_f32::__lp_lpfx_srandom2_f32(p0, p1, p2);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxSrandom2Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::srandom::srandom2_q32::__lp_lpfx_srandom2_q32(p0, p1, p2);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxSrandom3F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::srandom::srandom3_f32::__lp_lpfx_srandom3_f32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxSrandom3Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::srandom::srandom3_q32::__lp_lpfx_srandom3_q32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxSrandom3TileF32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0f32; 3];
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            let p4 = params[4].unwrap_f32();
            let p5 = params[5].unwrap_i32() as u32;
            lps_builtins::builtins::lpfx::generative::srandom::srandom3_tile_f32::__lp_lpfx_srandom3_tile_f32(buf_0.as_mut_ptr(), p1, p2, p3, p4, p5);
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxSrandom3TileQ32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0i32; 3];
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32();
            let p5 = params[5].unwrap_i32() as u32;
            lps_builtins::builtins::lpfx::generative::srandom::srandom3_tile_q32::__lp_lpfx_srandom3_tile_q32(buf_0.as_mut_ptr(), p1, p2, p3, p4, p5);
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxSrandom3VecF32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0f32; 3];
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_f32();
            let p4 = params[4].unwrap_i32() as u32;
            lps_builtins::builtins::lpfx::generative::srandom::srandom3_vec_f32::__lp_lpfx_srandom3_vec_f32(buf_0.as_mut_ptr(), p1, p2, p3, p4);
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxSrandom3VecQ32 => {
            let mem = linked_env_memory;
            let off_0 = params[0].unwrap_i32() as u32 as usize;
            let mut buf_0 = [0i32; 3];
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32();
            let p4 = params[4].unwrap_i32() as u32;
            lps_builtins::builtins::lpfx::generative::srandom::srandom3_vec_q32::__lp_lpfx_srandom3_vec_q32(buf_0.as_mut_ptr(), p1, p2, p3, p4);
            for (i, v) in buf_0.iter().enumerate() {
                mem.write(&mut caller, off_0 + i * 4, &v.to_le_bytes())
                    .map_err(|e| wasmtime::Error::msg(format!("builtin write-back: {e}")))?;
            }
            Ok(())
        }
        BuiltinId::LpLpfxWorley2F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::worley::worley2_f32::__lp_lpfx_worley2_f32(p0, p1, p2);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxWorley2Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::worley::worley2_q32::__lp_lpfx_worley2_q32(p0, p1, p2);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxWorley2ValueF32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::worley::worley2_value_f32::__lp_lpfx_worley2_value_f32(p0, p1, p2);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxWorley2ValueQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::worley::worley2_value_q32::__lp_lpfx_worley2_value_q32(p0, p1, p2);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxWorley3F32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::worley::worley3_f32::__lp_lpfx_worley3_f32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxWorley3Q32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::worley::worley3_q32::__lp_lpfx_worley3_q32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpfxWorley3ValueF32 => {
            let p0 = params[0].unwrap_f32();
            let p1 = params[1].unwrap_f32();
            let p2 = params[2].unwrap_f32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::worley::worley3_value_f32::__lp_lpfx_worley3_value_f32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::F32(r.to_bits());
            Ok(())
        }
        BuiltinId::LpLpfxWorley3ValueQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let p2 = params[2].unwrap_i32();
            let p3 = params[3].unwrap_i32() as u32;
            let r = lps_builtins::builtins::lpfx::generative::worley::worley3_value_q32::__lp_lpfx_worley3_value_q32(p0, p1, p2, p3);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFaddQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let r = lps_builtins::builtins::lpir::fadd_q32::__lp_lpir_fadd_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFdivQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let r = lps_builtins::builtins::lpir::fdiv_q32::__lp_lpir_fdiv_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFmulQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let r = lps_builtins::builtins::lpir::fmul_q32::__lp_lpir_fmul_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFnearestQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpir::fnearest_q32::__lp_lpir_fnearest_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFsqrtQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpir::fsqrt_q32::__lp_lpir_fsqrt_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirFsubQ32 => {
            let p0 = params[0].unwrap_i32();
            let p1 = params[1].unwrap_i32();
            let r = lps_builtins::builtins::lpir::fsub_q32::__lp_lpir_fsub_q32(p0, p1);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirItofSQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpir::itof_s_q32::__lp_lpir_itof_s_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpLpirItofUQ32 => {
            let p0 = params[0].unwrap_i32();
            let r = lps_builtins::builtins::lpir::itof_u_q32::__lp_lpir_itof_u_q32(p0);
            results[0] = wasmtime::Val::I32(r);
            Ok(())
        }
        BuiltinId::LpVmGetFuelQ32 => {
            let vmctx_word = params[0].unwrap_i32();
            let mem = linked_env_memory;
            let base = vmctx_word as u32 as usize;
            let mut buf = [0u8; 8];
            mem.read(&caller, base, &mut buf)
                .map_err(|e| wasmtime::Error::msg(format!("vmctx fuel read: {e}")))?;
            let fuel = u64::from_le_bytes(buf);
            results[0] = wasmtime::Val::I32(fuel as u32 as i32);
            Ok(())
        }
    }
}
