export DEBUG=1

(target/debug/lps-filetests-app test --target rv32fa.q32 array/phase/2-bounds-checking.glsl &> docs/fa3-errors/array/phase/2-bounds-checking.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 array/phase/7-function-parameters.glsl &> docs/fa3-errors/array/phase/7-function-parameters.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/common-floatbitstoint.glsl &> docs/fa3-errors/builtins/common-floatbitstoint.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/common-frexp.glsl &> docs/fa3-errors/builtins/common-frexp.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/common-intbitstofloat.glsl &> docs/fa3-errors/builtins/common-intbitstofloat.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/common-modf.glsl &> docs/fa3-errors/builtins/common-modf.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/common-roundeven.glsl &> docs/fa3-errors/builtins/common-roundeven.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/edge-exp-domain.glsl &> docs/fa3-errors/builtins/edge-exp-domain.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/edge-nan-inf-propagation.glsl &> docs/fa3-errors/builtins/edge-nan-inf-propagation.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/edge-precision.glsl &> docs/fa3-errors/builtins/edge-precision.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/edge-trig-domain.glsl &> docs/fa3-errors/builtins/edge-trig-domain.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/integer-bitcount.glsl &> docs/fa3-errors/builtins/integer-bitcount.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/integer-bitfieldextract.glsl &> docs/fa3-errors/builtins/integer-bitfieldextract.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/integer-bitfieldinsert.glsl &> docs/fa3-errors/builtins/integer-bitfieldinsert.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/integer-findmsb.glsl &> docs/fa3-errors/builtins/integer-findmsb.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/integer-imulextended.glsl &> docs/fa3-errors/builtins/integer-imulextended.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/integer-uaddcarry.glsl &> docs/fa3-errors/builtins/integer-uaddcarry.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/integer-umulextended.glsl &> docs/fa3-errors/builtins/integer-umulextended.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/integer-usubborrow.glsl &> docs/fa3-errors/builtins/integer-usubborrow.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/matrix-compmult.glsl &> docs/fa3-errors/builtins/matrix-compmult.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/matrix-determinant.glsl &> docs/fa3-errors/builtins/matrix-determinant.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/matrix-inverse.glsl &> docs/fa3-errors/builtins/matrix-inverse.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/matrix-outerproduct.glsl &> docs/fa3-errors/builtins/matrix-outerproduct.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/matrix-transpose.glsl &> docs/fa3-errors/builtins/matrix-transpose.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/pack-double.glsl &> docs/fa3-errors/builtins/pack-double.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/pack-half.glsl &> docs/fa3-errors/builtins/pack-half.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/pack-unorm.glsl &> docs/fa3-errors/builtins/pack-unorm.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/unpack-double.glsl &> docs/fa3-errors/builtins/unpack-double.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/unpack-half.glsl &> docs/fa3-errors/builtins/unpack-half.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 builtins/unpack-unorm.glsl &> docs/fa3-errors/builtins/unpack-unorm.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 const/array-size/struct-field.glsl &> docs/fa3-errors/const/array-size/struct-field.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/do_while/continue.glsl &> docs/fa3-errors/control/do_while/continue.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/do_while/edge_cases.glsl &> docs/fa3-errors/control/do_while/edge_cases.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/do_while/nested_if.glsl &> docs/fa3-errors/control/do_while/nested_if.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/do_while/nested_while.glsl &> docs/fa3-errors/control/do_while/nested_while.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/for/continue_nested.glsl &> docs/fa3-errors/control/for/continue_nested.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/for/nested_if.glsl &> docs/fa3-errors/control/for/nested_if.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/return/conditional.glsl &> docs/fa3-errors/control/return/conditional.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/return/early.glsl &> docs/fa3-errors/control/return/early.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/return/edge-cases.glsl &> docs/fa3-errors/control/return/edge-cases.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/ternary/edge_cases.glsl &> docs/fa3-errors/control/ternary/edge_cases.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/ternary/nested.glsl &> docs/fa3-errors/control/ternary/nested.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/ternary/precedence.glsl &> docs/fa3-errors/control/ternary/precedence.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/ternary/short_circuit.glsl &> docs/fa3-errors/control/ternary/short_circuit.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/ternary/type_conversions.glsl &> docs/fa3-errors/control/ternary/type_conversions.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/ternary/types.glsl &> docs/fa3-errors/control/ternary/types.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/while/continue.glsl &> docs/fa3-errors/control/while/continue.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/while/continue_nested.glsl &> docs/fa3-errors/control/while/continue_nested.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/while/edge_cases.glsl &> docs/fa3-errors/control/while/edge_cases.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/while/nested_do_while.glsl &> docs/fa3-errors/control/while/nested_do_while.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 control/while/nested_if.glsl &> docs/fa3-errors/control/while/nested_if.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 debug/palette-rainbow.glsl &> docs/fa3-errors/debug/palette-rainbow.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 debug/rainbow-noctrl.glsl &> docs/fa3-errors/debug/rainbow-noctrl.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 examples/rainbow.glsl &> docs/fa3-errors/examples/rainbow.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/call-multiple.glsl &> docs/fa3-errors/function/call-multiple.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/call-order.glsl &> docs/fa3-errors/function/call-order.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/call-return-value.glsl &> docs/fa3-errors/function/call-return-value.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/declare-prototype.glsl &> docs/fa3-errors/function/declare-prototype.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/edge-array-size-match.glsl &> docs/fa3-errors/function/edge-array-size-match.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/edge-const-out-error.glsl &> docs/fa3-errors/function/edge-const-out-error.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/edge-inout-both.glsl &> docs/fa3-errors/function/edge-inout-both.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/edge-lvalue-out.glsl &> docs/fa3-errors/function/edge-lvalue-out.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/edge-out-not-read.glsl &> docs/fa3-errors/function/edge-out-not-read.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/edge-return-type-match.glsl &> docs/fa3-errors/function/edge-return-type-match.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/forward-declare.glsl &> docs/fa3-errors/function/forward-declare.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/overload-same-name.glsl &> docs/fa3-errors/function/overload-same-name.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/param-array.glsl &> docs/fa3-errors/function/param-array.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/param-default-in.glsl &> docs/fa3-errors/function/param-default-in.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/param-in.glsl &> docs/fa3-errors/function/param-in.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/param-inout.glsl &> docs/fa3-errors/function/param-inout.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/param-many.glsl &> docs/fa3-errors/function/param-many.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/param-mixed.glsl &> docs/fa3-errors/function/param-mixed.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/param-out-array.glsl &> docs/fa3-errors/function/param-out-array.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/param-struct.glsl &> docs/fa3-errors/function/param-struct.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/param-unnamed/int.glsl &> docs/fa3-errors/function/param-unnamed/int.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/recursive-static-error.glsl &> docs/fa3-errors/function/recursive-static-error.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/return-array.glsl &> docs/fa3-errors/function/return-array.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/return-early.glsl &> docs/fa3-errors/function/return-early.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/return-exact-match.glsl &> docs/fa3-errors/function/return-exact-match.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/return-multiple.glsl &> docs/fa3-errors/function/return-multiple.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/return-struct.glsl &> docs/fa3-errors/function/return-struct.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/return-while-loop.glsl &> docs/fa3-errors/function/return-while-loop.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/scope-global.glsl &> docs/fa3-errors/function/scope-global.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 function/scope-local.glsl &> docs/fa3-errors/function/scope-local.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/access-from-function.glsl &> docs/fa3-errors/global/access-from-function.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/access-from-main.glsl &> docs/fa3-errors/global/access-from-main.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/access-read.glsl &> docs/fa3-errors/global/access-read.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/access-write.glsl &> docs/fa3-errors/global/access-write.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/declare-buffer.glsl &> docs/fa3-errors/global/declare-buffer.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/declare-in.glsl &> docs/fa3-errors/global/declare-in.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/declare-out.glsl &> docs/fa3-errors/global/declare-out.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/declare-shared.glsl &> docs/fa3-errors/global/declare-shared.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/declare-simple.glsl &> docs/fa3-errors/global/declare-simple.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/declare-uniform.glsl &> docs/fa3-errors/global/declare-uniform.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/edge-empty-declaration.glsl &> docs/fa3-errors/global/edge-empty-declaration.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/edge-in-write-error.glsl &> docs/fa3-errors/global/edge-in-write-error.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/edge-multiple-qualifiers-error.glsl &> docs/fa3-errors/global/edge-multiple-qualifiers-error.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/edge-no-storage-qualifier.glsl &> docs/fa3-errors/global/edge-no-storage-qualifier.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/edge-out-read-error.glsl &> docs/fa3-errors/global/edge-out-read-error.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/edge-uniform-write-error.glsl &> docs/fa3-errors/global/edge-uniform-write-error.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/edge-uninitialized-read.glsl &> docs/fa3-errors/global/edge-uninitialized-read.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/forward-reference.glsl &> docs/fa3-errors/global/forward-reference.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/in-readonly.glsl &> docs/fa3-errors/global/in-readonly.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/initialize-simple.glsl &> docs/fa3-errors/global/initialize-simple.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/initialize-undefined.glsl &> docs/fa3-errors/global/initialize-undefined.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/initialize-uniform.glsl &> docs/fa3-errors/global/initialize-uniform.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/multiple-declare.glsl &> docs/fa3-errors/global/multiple-declare.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/out-writeonly.glsl &> docs/fa3-errors/global/out-writeonly.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/redeclare-error.glsl &> docs/fa3-errors/global/redeclare-error.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/scope-global.glsl &> docs/fa3-errors/global/scope-global.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/scope-nested.glsl &> docs/fa3-errors/global/scope-nested.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/scope-shadowing.glsl &> docs/fa3-errors/global/scope-shadowing.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/shared-array-size.glsl &> docs/fa3-errors/global/shared-array-size.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/shared-globals.glsl &> docs/fa3-errors/global/shared-globals.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/shared-struct-match.glsl &> docs/fa3-errors/global/shared-struct-match.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/type-array.glsl &> docs/fa3-errors/global/type-array.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/type-matrix.glsl &> docs/fa3-errors/global/type-matrix.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/type-scalar.glsl &> docs/fa3-errors/global/type-scalar.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/type-struct.glsl &> docs/fa3-errors/global/type-struct.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/type-vector.glsl &> docs/fa3-errors/global/type-vector.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/uniform-no-init-error.glsl &> docs/fa3-errors/global/uniform-no-init-error.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 global/uniform-readonly.glsl &> docs/fa3-errors/global/uniform-readonly.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 lpfn/lp_hsv2rgb.glsl &> docs/fa3-errors/lpfn/lp_hsv2rgb.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 lpfn/lp_hue2rgb.glsl &> docs/fa3-errors/lpfn/lp_hue2rgb.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 lpfn/lp_rgb2hsv.glsl &> docs/fa3-errors/lpfn/lp_rgb2hsv.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 lpfn/lp_saturate.glsl &> docs/fa3-errors/lpfn/lp_saturate.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat2/incdec-matrix-column.glsl &> docs/fa3-errors/matrix/mat2/incdec-matrix-column.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat2/incdec-matrix-element.glsl &> docs/fa3-errors/matrix/mat2/incdec-matrix-element.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat2/op-add-assign.glsl &> docs/fa3-errors/matrix/mat2/op-add-assign.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat2/op-assign.glsl &> docs/fa3-errors/matrix/mat2/op-assign.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat2/op-multiply-assign.glsl &> docs/fa3-errors/matrix/mat2/op-multiply-assign.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat2/op-multiply.glsl &> docs/fa3-errors/matrix/mat2/op-multiply.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat3/incdec-matrix-column.glsl &> docs/fa3-errors/matrix/mat3/incdec-matrix-column.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat3/incdec-matrix-element.glsl &> docs/fa3-errors/matrix/mat3/incdec-matrix-element.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat3/op-add-assign.glsl &> docs/fa3-errors/matrix/mat3/op-add-assign.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat3/op-assign.glsl &> docs/fa3-errors/matrix/mat3/op-assign.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat3/op-multiply-assign.glsl &> docs/fa3-errors/matrix/mat3/op-multiply-assign.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat3/op-multiply.glsl &> docs/fa3-errors/matrix/mat3/op-multiply.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat3/op-subtract-assign.glsl &> docs/fa3-errors/matrix/mat3/op-subtract-assign.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat4/fn-determinant.glsl &> docs/fa3-errors/matrix/mat4/fn-determinant.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat4/from-matrix.glsl &> docs/fa3-errors/matrix/mat4/from-matrix.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat4/from-scalar.glsl &> docs/fa3-errors/matrix/mat4/from-scalar.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat4/incdec-matrix-column.glsl &> docs/fa3-errors/matrix/mat4/incdec-matrix-column.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat4/incdec-matrix-element.glsl &> docs/fa3-errors/matrix/mat4/incdec-matrix-element.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat4/op-add-assign.glsl &> docs/fa3-errors/matrix/mat4/op-add-assign.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat4/op-assign.glsl &> docs/fa3-errors/matrix/mat4/op-assign.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat4/op-incdec.glsl &> docs/fa3-errors/matrix/mat4/op-incdec.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat4/op-multiply-assign.glsl &> docs/fa3-errors/matrix/mat4/op-multiply-assign.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat4/op-multiply.glsl &> docs/fa3-errors/matrix/mat4/op-multiply.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 matrix/mat4/op-subtract-assign.glsl &> docs/fa3-errors/matrix/mat4/op-subtract-assign.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 operators/incdec-component.glsl &> docs/fa3-errors/operators/incdec-component.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 operators/incdec-matrix-column.glsl &> docs/fa3-errors/operators/incdec-matrix-column.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 operators/incdec-matrix-element.glsl &> docs/fa3-errors/operators/incdec-matrix-element.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 operators/incdec-matrix.glsl &> docs/fa3-errors/operators/incdec-matrix.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 operators/incdec-vector.glsl &> docs/fa3-errors/operators/incdec-vector.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 operators/predec-component.glsl &> docs/fa3-errors/operators/predec-component.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 scalar/bool/to-float.glsl &> docs/fa3-errors/scalar/bool/to-float.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 scalar/float/from-bool.glsl &> docs/fa3-errors/scalar/float/from-bool.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 struct/access-scalar.glsl &> docs/fa3-errors/struct/access-scalar.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 struct/access-vector.glsl &> docs/fa3-errors/struct/access-vector.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 struct/assign-simple.glsl &> docs/fa3-errors/struct/assign-simple.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 struct/constructor-nested.glsl &> docs/fa3-errors/struct/constructor-nested.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 struct/constructor-simple.glsl &> docs/fa3-errors/struct/constructor-simple.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 struct/constructor-vectors.glsl &> docs/fa3-errors/struct/constructor-vectors.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 struct/define-nested.glsl &> docs/fa3-errors/struct/define-nested.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 struct/define-simple.glsl &> docs/fa3-errors/struct/define-simple.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 struct/define-vector.glsl &> docs/fa3-errors/struct/define-vector.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/bvec2/fn-mix.glsl &> docs/fa3-errors/vec/bvec2/fn-mix.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/bvec2/from-scalar.glsl &> docs/fa3-errors/vec/bvec2/from-scalar.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/bvec2/index-variable-bounds.glsl &> docs/fa3-errors/vec/bvec2/index-variable-bounds.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/bvec2/index-variable-valid.glsl &> docs/fa3-errors/vec/bvec2/index-variable-valid.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/bvec2/to-float.glsl &> docs/fa3-errors/vec/bvec2/to-float.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/bvec3/fn-mix.glsl &> docs/fa3-errors/vec/bvec3/fn-mix.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/bvec3/from-scalar.glsl &> docs/fa3-errors/vec/bvec3/from-scalar.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/bvec4/fn-mix.glsl &> docs/fa3-errors/vec/bvec4/fn-mix.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/bvec4/from-scalar.glsl &> docs/fa3-errors/vec/bvec4/from-scalar.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/ivec2/fn-max.gen.glsl &> docs/fa3-errors/vec/ivec2/fn-max.gen.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/ivec2/fn-min.gen.glsl &> docs/fa3-errors/vec/ivec2/fn-min.gen.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/ivec3/fn-max.gen.glsl &> docs/fa3-errors/vec/ivec3/fn-max.gen.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/ivec3/fn-min.gen.glsl &> docs/fa3-errors/vec/ivec3/fn-min.gen.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/ivec4/fn-max.gen.glsl &> docs/fa3-errors/vec/ivec4/fn-max.gen.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/ivec4/fn-min.gen.glsl &> docs/fa3-errors/vec/ivec4/fn-min.gen.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/uvec2/fn-max.gen.glsl &> docs/fa3-errors/vec/uvec2/fn-max.gen.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/uvec2/fn-min.gen.glsl &> docs/fa3-errors/vec/uvec2/fn-min.gen.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/uvec3/fn-max.gen.glsl &> docs/fa3-errors/vec/uvec3/fn-max.gen.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/uvec3/fn-min.gen.glsl &> docs/fa3-errors/vec/uvec3/fn-min.gen.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/uvec3/from-uvec.glsl &> docs/fa3-errors/vec/uvec3/from-uvec.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/uvec4/fn-max.gen.glsl &> docs/fa3-errors/vec/uvec4/fn-max.gen.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/uvec4/fn-min.gen.glsl &> docs/fa3-errors/vec/uvec4/fn-min.gen.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/vec3/from-scalar.glsl &> docs/fa3-errors/vec/vec3/from-scalar.glsl)&
(target/debug/lps-filetests-app test --target rv32fa.q32 vec/vec4/from-scalar.glsl &> docs/fa3-errors/vec/vec4/from-scalar.glsl)&