//! WASM valtypes for each `BuiltinId` import (wasm32, `extern "C"` layout).
//!
//! AUTO-GENERATED by lp-glsl-builtins-gen-app. Do not edit manually.
//!
//! Regenerate: `cargo run -p lp-glsl-builtins-gen-app` or `scripts/build-builtins.sh`

extern crate alloc;

use alloc::vec;
use alloc::vec::Vec;
use lp_glsl_builtin_ids::BuiltinId;
use wasm_encoder::ValType;

/// Parameter and result WASM types for the imported builtin function.
pub(super) fn wasm_import_val_types(builtin: BuiltinId) -> (Vec<ValType>, Vec<ValType>) {
    match builtin {
        BuiltinId::LpQ32Acos => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Acosh => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Add => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Asin => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Asinh => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Atan => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Atan2 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Atanh => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Cos => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Cosh => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Div => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Exp => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Exp2 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Fma => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpQ32Inversesqrt => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Ldexp => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Log => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Log2 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Mod => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Mul => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Pow => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Round => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Roundeven => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Sin => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Sinh => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Sqrt => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Sub => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Tan => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpQ32Tanh => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpfxFbm2F32 => (
            vec![ValType::F32, ValType::F32, ValType::I32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpfxFbm2Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpfxFbm3F32 => (
            vec![
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::F32],
        ),
        BuiltinId::LpfxFbm3Q32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::I32],
        ),
        BuiltinId::LpfxFbm3TileF32 => (
            vec![
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::F32],
        ),
        BuiltinId::LpfxFbm3TileQ32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::I32],
        ),
        BuiltinId::LpfxGnoise1F32 => (vec![ValType::F32, ValType::I32], vec![ValType::F32]),
        BuiltinId::LpfxGnoise1Q32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpfxGnoise2F32 => (
            vec![ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpfxGnoise2Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpfxGnoise3F32 => (
            vec![ValType::F32, ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpfxGnoise3Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpfxGnoise3TileF32 => (
            vec![
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
            ],
            vec![ValType::F32],
        ),
        BuiltinId::LpfxGnoise3TileQ32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::I32],
        ),
        BuiltinId::LpfxHash1 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpfxHash2 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpfxHash3 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpfxHsv2rgbF32 => (
            vec![ValType::I32, ValType::F32, ValType::F32, ValType::F32],
            Vec::new(),
        ),
        BuiltinId::LpfxHsv2rgbQ32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            Vec::new(),
        ),
        BuiltinId::LpfxHsv2rgbVec4F32 => (
            vec![
                ValType::I32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpfxHsv2rgbVec4Q32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpfxHue2rgbF32 => (vec![ValType::I32, ValType::F32], Vec::new()),
        BuiltinId::LpfxHue2rgbQ32 => (vec![ValType::I32, ValType::I32], Vec::new()),
        BuiltinId::LpfxPsrdnoise2F32 => (
            vec![
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::F32],
        ),
        BuiltinId::LpfxPsrdnoise2Q32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::I32],
        ),
        BuiltinId::LpfxPsrdnoise3F32 => (
            vec![
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::F32],
        ),
        BuiltinId::LpfxPsrdnoise3Q32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::I32],
        ),
        BuiltinId::LpfxRandom1F32 => (vec![ValType::F32, ValType::I32], vec![ValType::F32]),
        BuiltinId::LpfxRandom1Q32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpfxRandom2F32 => (
            vec![ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpfxRandom2Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpfxRandom3F32 => (
            vec![ValType::F32, ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpfxRandom3Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpfxRgb2hsvF32 => (
            vec![ValType::I32, ValType::F32, ValType::F32, ValType::F32],
            Vec::new(),
        ),
        BuiltinId::LpfxRgb2hsvQ32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            Vec::new(),
        ),
        BuiltinId::LpfxRgb2hsvVec4F32 => (
            vec![
                ValType::I32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpfxRgb2hsvVec4Q32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpfxSaturateF32 => (vec![ValType::F32], vec![ValType::F32]),
        BuiltinId::LpfxSaturateQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpfxSaturateVec3F32 => (
            vec![ValType::I32, ValType::F32, ValType::F32, ValType::F32],
            Vec::new(),
        ),
        BuiltinId::LpfxSaturateVec3Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            Vec::new(),
        ),
        BuiltinId::LpfxSaturateVec4F32 => (
            vec![
                ValType::I32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpfxSaturateVec4Q32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpfxSnoise1F32 => (vec![ValType::F32, ValType::I32], vec![ValType::F32]),
        BuiltinId::LpfxSnoise1Q32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpfxSnoise2F32 => (
            vec![ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpfxSnoise2Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpfxSnoise3F32 => (
            vec![ValType::F32, ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpfxSnoise3Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpfxSrandom1F32 => (vec![ValType::F32, ValType::I32], vec![ValType::F32]),
        BuiltinId::LpfxSrandom1Q32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpfxSrandom2F32 => (
            vec![ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpfxSrandom2Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpfxSrandom3F32 => (
            vec![ValType::F32, ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpfxSrandom3Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpfxSrandom3TileF32 => (
            vec![
                ValType::I32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpfxSrandom3TileQ32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpfxSrandom3VecF32 => (
            vec![
                ValType::I32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpfxSrandom3VecQ32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpfxWorley2F32 => (
            vec![ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpfxWorley2Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpfxWorley2ValueF32 => (
            vec![ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpfxWorley2ValueQ32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpfxWorley3F32 => (
            vec![ValType::F32, ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpfxWorley3Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpfxWorley3ValueF32 => (
            vec![ValType::F32, ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpfxWorley3ValueQ32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
    }
}
