// LightPlayer LPFX: forward declarations for Naga (bodies are WASM imports).
uint __lp_get_fuel();
uint lpfn_hash(uint x, uint seed);
uint lpfn_hash(uvec2 xy, uint seed);
uint lpfn_hash(uvec3 xyz, uint seed);
float lpfn_saturate(float x);
vec3 lpfn_saturate(vec3 v);
vec4 lpfn_saturate(vec4 v);
vec3 lpfn_hue2rgb(float hue);
vec3 lpfn_hsv2rgb(vec3 hsv);
vec4 lpfn_hsv2rgb(vec4 hsv);
vec3 lpfn_rgb2hsv(vec3 rgb);
vec4 lpfn_rgb2hsv(vec4 rgb);
float lpfn_fbm(vec2 p, int octaves, uint seed);
float lpfn_fbm(vec3 p, int octaves, uint seed);
float lpfn_fbm(vec3 p, float tileLength, int octaves, uint seed);
float lpfn_gnoise(float x, uint seed);
float lpfn_gnoise(vec2 p, uint seed);
float lpfn_gnoise(vec3 p, uint seed);
float lpfn_gnoise(vec3 p, float tileLength, uint seed);
float lpfn_random(float x, uint seed);
float lpfn_random(vec2 p, uint seed);
float lpfn_random(vec3 p, uint seed);
float lpfn_snoise(float x, uint seed);
float lpfn_snoise(vec2 p, uint seed);
float lpfn_snoise(vec3 p, uint seed);
float lpfn_srandom(float x, uint seed);
float lpfn_srandom(vec2 p, uint seed);
float lpfn_srandom(vec3 p, uint seed);
vec3 lpfn_srandom3_tile(vec3 p, float tileLength, uint seed);
vec3 lpfn_srandom3_vec(vec3 p, uint seed);
float lpfn_worley(vec2 p, uint seed);
float lpfn_worley(vec3 p, uint seed);
float lpfn_worley_value(vec2 p, uint seed);
float lpfn_worley_value(vec3 p, uint seed);
float lpfn_psrdnoise(vec2 x, vec2 period, float alpha, out vec2 gradient, uint seed);
float lpfn_psrdnoise(vec3 x, vec3 period, float alpha, out vec3 gradient, uint seed);
