// LightPlayer LPFX: forward declarations for Naga (bodies are WASM imports).
uint lpfx_hash(uint x, uint seed);
uint lpfx_hash(uvec2 xy, uint seed);
uint lpfx_hash(uvec3 xyz, uint seed);
float lpfx_saturate(float x);
vec3 lpfx_saturate(vec3 v);
vec4 lpfx_saturate(vec4 v);
vec3 lpfx_hue2rgb(float hue);
vec3 lpfx_hsv2rgb(vec3 hsv);
vec4 lpfx_hsv2rgb(vec4 hsv);
vec3 lpfx_rgb2hsv(vec3 rgb);
vec4 lpfx_rgb2hsv(vec4 rgb);
float lpfx_fbm(vec2 p, int octaves, uint seed);
float lpfx_fbm(vec3 p, int octaves, uint seed);
float lpfx_fbm(vec3 p, float tileLength, int octaves, uint seed);
float lpfx_gnoise(float x, uint seed);
float lpfx_gnoise(vec2 p, uint seed);
float lpfx_gnoise(vec3 p, uint seed);
float lpfx_gnoise(vec3 p, float tileLength, uint seed);
float lpfx_random(float x, uint seed);
float lpfx_random(vec2 p, uint seed);
float lpfx_random(vec3 p, uint seed);
float lpfx_snoise(float x, uint seed);
float lpfx_snoise(vec2 p, uint seed);
float lpfx_snoise(vec3 p, uint seed);
float lpfx_srandom(float x, uint seed);
float lpfx_srandom(vec2 p, uint seed);
float lpfx_srandom(vec3 p, uint seed);
vec3 lpfx_srandom3_tile(vec3 p, float tileLength, uint seed);
vec3 lpfx_srandom3_vec(vec3 p, uint seed);
float lpfx_worley(vec2 p, uint seed);
float lpfx_worley(vec3 p, uint seed);
float lpfx_worley_value(vec2 p, uint seed);
float lpfx_worley_value(vec3 p, uint seed);
float lpfx_psrdnoise(vec2 x, vec2 period, float alpha, out vec2 gradient, uint seed);
float lpfx_psrdnoise(vec3 x, vec3 period, float alpha, out vec3 gradient, uint seed);
