kind = "Project"
name = "fluid"

[nodes.output]
def = { path = "./output.toml" }

[nodes.clock]
def = { path = "./clock.toml" }

[nodes.compute]
def = { path = "./compute.toml" }

[nodes.fluid]
def = { path = "./fluid.toml" }

[nodes.fixture]
def = { path = "./fixture.toml" }
