kind = "project"
name = "fluid"

[nodes.output]
artifact = "./output.toml"

[nodes.clock]
kind = "clock"

[nodes.compute]
artifact = "./compute.toml"

[nodes.fluid]
artifact = "./fluid.toml"

[nodes.fixture]
artifact = "./fixture.toml"
