kind = "Project"
name = "fluid"

[nodes.output]
ref = "./output.toml"

[nodes.clock]
ref = "./clock.toml"

[nodes.compute]
ref = "./compute.toml"

[nodes.fluid]
ref = "./fluid.toml"

[nodes.fixture]
ref = "./fixture.toml"
