kind = "Project"
name = "button-playlist"

[nodes.output]
ref = "./output.toml"

[nodes.clock]
ref = "./clock.toml"

[nodes.button]
ref = "./button.toml"

[nodes.playlist]
ref = "./playlist.toml"

[nodes.fixture]
ref = "./fixture.toml"
