kind = "Shader"
source = { path = "shader.glsl" }
render_order = 0

[bindings.output]
target = "bus#visual.out"

[glsl_opts]
add_sub = "wrapping"
mul = "wrapping"
div = "reciprocal"

[consumed_slots.time]
kind = "value"
value = "f32"
default = 0.0
label = "Time"
description = "Project clock time in seconds"
