//! GLSL / LPIR / LPFX name → `BuiltinId` for Q32 WASM imports.
//!
//! AUTO-GENERATED by lps-builtins-gen-app. Do not edit manually.
//!
//! - `glsl_q32_math_builtin_id`: `@glsl::*` scalar imports.
//! - `lpir_q32_builtin_id`: `@lpir::*` library ops (e.g. `sqrt`).
//! - `glsl_lpfx_q32_builtin_id`: `lpfx_*` overloads keyed by parameter types.
//!
//! Regenerate: `cargo run -p lps-builtins-gen-app` or `scripts/build-builtins.sh`

use super::BuiltinId;

/// Parameter types for LPFX overload resolution (matches GLSL, not flattened WASM).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum GlslParamKind {
    Bool,
    Int,
    UInt,
    Float,
    Vec2,
    Vec3,
    Vec4,
    IVec2,
    IVec3,
    IVec4,
    UVec2,
    UVec3,
    UVec4,
    BVec2,
    BVec3,
    BVec4,
}

/// Map `@glsl::*` import name + **AST argument count** to a scalar builtin.
/// Returns `None` for builtins implemented inline in WASM (e.g. `clamp`) or unknown names.
pub fn glsl_q32_math_builtin_id(name: &str, arg_count: usize) -> Option<BuiltinId> {
    match (name, arg_count) {
        ("acos", 1) => Some(BuiltinId::LpGlslAcosQ32),
        ("acosh", 1) => Some(BuiltinId::LpGlslAcoshQ32),
        ("asin", 1) => Some(BuiltinId::LpGlslAsinQ32),
        ("asinh", 1) => Some(BuiltinId::LpGlslAsinhQ32),
        ("atan", 2) => Some(BuiltinId::LpGlslAtan2Q32),
        ("atan2", 2) => Some(BuiltinId::LpGlslAtan2Q32),
        ("atan", 1) => Some(BuiltinId::LpGlslAtanQ32),
        ("atanh", 1) => Some(BuiltinId::LpGlslAtanhQ32),
        ("cos", 1) => Some(BuiltinId::LpGlslCosQ32),
        ("cosh", 1) => Some(BuiltinId::LpGlslCoshQ32),
        ("exp2", 1) => Some(BuiltinId::LpGlslExp2Q32),
        ("exp", 1) => Some(BuiltinId::LpGlslExpQ32),
        ("fma", 3) => Some(BuiltinId::LpGlslFmaQ32),
        ("inversesqrt", 1) => Some(BuiltinId::LpGlslInversesqrtQ32),
        ("ldexp", 2) => Some(BuiltinId::LpGlslLdexpQ32),
        ("log2", 1) => Some(BuiltinId::LpGlslLog2Q32),
        ("log", 1) => Some(BuiltinId::LpGlslLogQ32),
        ("mod", 2) => Some(BuiltinId::LpGlslModQ32),
        ("pow", 2) => Some(BuiltinId::LpGlslPowQ32),
        ("round", 1) => Some(BuiltinId::LpGlslRoundQ32),
        ("sin", 1) => Some(BuiltinId::LpGlslSinQ32),
        ("sinh", 1) => Some(BuiltinId::LpGlslSinhQ32),
        ("tan", 1) => Some(BuiltinId::LpGlslTanQ32),
        ("tanh", 1) => Some(BuiltinId::LpGlslTanhQ32),
        _ => None,
    }
}

/// Map `@lpir::*` import name + argument count to a Q32 builtin.
pub fn lpir_q32_builtin_id(name: &str, arg_count: usize) -> Option<BuiltinId> {
    match (name, arg_count) {
        ("fabs", 1) => Some(BuiltinId::LpLpirFabsQ32),
        ("fadd", 2) => Some(BuiltinId::LpLpirFaddQ32),
        ("fceil", 1) => Some(BuiltinId::LpLpirFceilQ32),
        ("fdiv", 2) => Some(BuiltinId::LpLpirFdivQ32),
        ("ffloor", 1) => Some(BuiltinId::LpLpirFfloorQ32),
        ("fmax", 2) => Some(BuiltinId::LpLpirFmaxQ32),
        ("fmin", 2) => Some(BuiltinId::LpLpirFminQ32),
        ("fmul", 2) => Some(BuiltinId::LpLpirFmulQ32),
        ("fnearest", 1) => Some(BuiltinId::LpLpirFnearestQ32),
        ("sqrt", 1) => Some(BuiltinId::LpLpirFsqrtQ32),
        ("fsub", 2) => Some(BuiltinId::LpLpirFsubQ32),
        ("ftoi_sat_s", 1) => Some(BuiltinId::LpLpirFtoiSatSQ32),
        ("ftoi_sat_u", 1) => Some(BuiltinId::LpLpirFtoiSatUQ32),
        ("ftrunc", 1) => Some(BuiltinId::LpLpirFtruncQ32),
        ("itof_s", 1) => Some(BuiltinId::LpLpirItofSQ32),
        ("itof_u", 1) => Some(BuiltinId::LpLpirItofUQ32),
        _ => None,
    }
}

/// Map `@vm::*` import name + user-visible argument count to a Q32 builtin.
pub fn vm_q32_builtin_id(name: &str, arg_count: usize) -> Option<BuiltinId> {
    match (name, arg_count) {
        ("__lp_get_fuel", 0) => Some(BuiltinId::LpVmGetFuelQ32),
        _ => None,
    }
}

/// Map `lpfx_*` name + parameter type list to the Q32 `BuiltinId`.
pub fn glsl_lpfx_q32_builtin_id(name: &str, params: &[GlslParamKind]) -> Option<BuiltinId> {
    match (name, params) {
        ("lpfx_fbm", &[GlslParamKind::Vec2, GlslParamKind::Int, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfxFbm2Q32)
        }
        (
            "lpfx_fbm",
            &[
                GlslParamKind::Vec3,
                GlslParamKind::Float,
                GlslParamKind::Int,
                GlslParamKind::UInt,
            ],
        ) => Some(BuiltinId::LpLpfxFbm3TileQ32),
        ("lpfx_fbm", &[GlslParamKind::Vec3, GlslParamKind::Int, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfxFbm3Q32)
        }
        ("lpfx_gnoise", &[GlslParamKind::Float, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfxGnoise1Q32)
        }
        ("lpfx_gnoise", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfxGnoise2Q32)
        }
        (
            "lpfx_gnoise",
            &[
                GlslParamKind::Vec3,
                GlslParamKind::Float,
                GlslParamKind::UInt,
            ],
        ) => Some(BuiltinId::LpLpfxGnoise3TileQ32),
        ("lpfx_gnoise", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfxGnoise3Q32)
        }
        ("lpfx_hash", &[GlslParamKind::UInt, GlslParamKind::UInt]) => Some(BuiltinId::LpLpfxHash1),
        ("lpfx_hash", &[GlslParamKind::UVec2, GlslParamKind::UInt]) => Some(BuiltinId::LpLpfxHash2),
        ("lpfx_hash", &[GlslParamKind::UVec3, GlslParamKind::UInt]) => Some(BuiltinId::LpLpfxHash3),
        ("lpfx_hsv2rgb", &[GlslParamKind::Vec3]) => Some(BuiltinId::LpLpfxHsv2rgbQ32),
        ("lpfx_hsv2rgb", &[GlslParamKind::Vec4]) => Some(BuiltinId::LpLpfxHsv2rgbVec4Q32),
        ("lpfx_hue2rgb", &[GlslParamKind::Float]) => Some(BuiltinId::LpLpfxHue2rgbQ32),
        (
            "lpfx_psrdnoise",
            &[
                GlslParamKind::Vec2,
                GlslParamKind::Vec2,
                GlslParamKind::Float,
                GlslParamKind::Vec2,
                GlslParamKind::UInt,
            ],
        ) => Some(BuiltinId::LpLpfxPsrdnoise2Q32),
        (
            "lpfx_psrdnoise",
            &[
                GlslParamKind::Vec3,
                GlslParamKind::Vec3,
                GlslParamKind::Float,
                GlslParamKind::Vec3,
                GlslParamKind::UInt,
            ],
        ) => Some(BuiltinId::LpLpfxPsrdnoise3Q32),
        ("lpfx_random", &[GlslParamKind::Float, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfxRandom1Q32)
        }
        ("lpfx_random", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfxRandom2Q32)
        }
        ("lpfx_random", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfxRandom3Q32)
        }
        ("lpfx_rgb2hsv", &[GlslParamKind::Vec3]) => Some(BuiltinId::LpLpfxRgb2hsvQ32),
        ("lpfx_rgb2hsv", &[GlslParamKind::Vec4]) => Some(BuiltinId::LpLpfxRgb2hsvVec4Q32),
        ("lpfx_saturate", &[GlslParamKind::Float]) => Some(BuiltinId::LpLpfxSaturateQ32),
        ("lpfx_saturate", &[GlslParamKind::Vec3]) => Some(BuiltinId::LpLpfxSaturateVec3Q32),
        ("lpfx_saturate", &[GlslParamKind::Vec4]) => Some(BuiltinId::LpLpfxSaturateVec4Q32),
        ("lpfx_snoise", &[GlslParamKind::Float, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfxSnoise1Q32)
        }
        ("lpfx_snoise", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfxSnoise2Q32)
        }
        ("lpfx_snoise", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfxSnoise3Q32)
        }
        ("lpfx_srandom", &[GlslParamKind::Float, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfxSrandom1Q32)
        }
        ("lpfx_srandom", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfxSrandom2Q32)
        }
        ("lpfx_srandom", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfxSrandom3Q32)
        }
        (
            "lpfx_srandom3_tile",
            &[
                GlslParamKind::Vec3,
                GlslParamKind::Float,
                GlslParamKind::UInt,
            ],
        ) => Some(BuiltinId::LpLpfxSrandom3TileQ32),
        ("lpfx_srandom3_vec", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfxSrandom3VecQ32)
        }
        ("lpfx_worley", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfxWorley2Q32)
        }
        ("lpfx_worley", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfxWorley3Q32)
        }
        ("lpfx_worley_value", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfxWorley2ValueQ32)
        }
        ("lpfx_worley_value", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfxWorley3ValueQ32)
        }
        _ => None,
    }
}

#[cfg(test)]
mod glsl_builtin_mapping_tests {
    use super::{
        GlslParamKind, glsl_lpfx_q32_builtin_id, glsl_q32_math_builtin_id, lpir_q32_builtin_id,
        vm_q32_builtin_id,
    };
    use crate::BuiltinId;

    #[test]
    fn q32_sin() {
        assert_eq!(
            glsl_q32_math_builtin_id("sin", 1),
            Some(BuiltinId::LpGlslSinQ32)
        );
    }

    #[test]
    fn q32_atan_two_args_is_atan2_import() {
        assert_eq!(
            glsl_q32_math_builtin_id("atan", 2),
            Some(BuiltinId::LpGlslAtan2Q32)
        );
    }

    #[test]
    fn lpir_sqrt() {
        assert_eq!(
            lpir_q32_builtin_id("sqrt", 1),
            Some(BuiltinId::LpLpirFsqrtQ32)
        );
    }

    #[test]
    fn vm_get_fuel() {
        assert_eq!(
            vm_q32_builtin_id("__lp_get_fuel", 0),
            Some(BuiltinId::LpVmGetFuelQ32)
        );
    }

    #[test]
    fn lpfx_fbm_vec2() {
        assert_eq!(
            glsl_lpfx_q32_builtin_id(
                "lpfx_fbm",
                &[GlslParamKind::Vec2, GlslParamKind::Int, GlslParamKind::UInt],
            ),
            Some(BuiltinId::LpLpfxFbm2Q32)
        );
    }
}
