kind = "project"
uid = "rocaille"
name = "rocaille"

[nodes.output]
artifact = "./output.toml"

[nodes.clock]
kind = "clock"

[nodes.texture]
artifact = "./texture.toml"

[nodes.shader]
artifact = "./shader.toml"

[nodes.fixture]
artifact = "./fixture.toml"
