//! Golden snapshots for selected `__lp_lpfn_*_q32` entry points (raw fixed-point I/O).

mod util;

use lps_builtins::builtins::glsl::sincos_q32::lps_sincos_q32_pair;
use lps_builtins::builtins::lpfn::color::space::hsv2rgb_q32::__lp_lpfn_hsv2rgb_q32;
use lps_builtins::builtins::lpfn::color::space::rgb2hsv_q32::__lp_lpfn_rgb2hsv_q32;
use lps_builtins::builtins::lpfn::generative::fbm::fbm2_q32::__lp_lpfn_fbm2_q32;
use lps_builtins::builtins::lpfn::generative::fbm::fbm3_q32::__lp_lpfn_fbm3_q32;
use lps_builtins::builtins::lpfn::generative::gnoise::gnoise2_q32::__lp_lpfn_gnoise2_q32;
use lps_builtins::builtins::lpfn::generative::gnoise::gnoise3_q32::__lp_lpfn_gnoise3_q32;
use lps_builtins::builtins::lpfn::generative::psrdnoise::psrdnoise2_q32::__lp_lpfn_psrdnoise2_q32;
use lps_builtins::builtins::lpfn::generative::psrdnoise::psrdnoise3_q32::__lp_lpfn_psrdnoise3_q32;
use lps_builtins::builtins::lpfn::generative::snoise::snoise2_q32::__lp_lpfn_snoise2_q32;
use lps_builtins::builtins::lpfn::generative::snoise::snoise3_q32::__lp_lpfn_snoise3_q32;
use lps_builtins::builtins::lpfn::generative::worley::worley2_q32::__lp_lpfn_worley2_q32;
use lps_builtins::builtins::lpfn::generative::worley::worley2_value_q32::__lp_lpfn_worley2_value_q32;
use lps_builtins::builtins::lpfn::generative::worley::worley3_q32::__lp_lpfn_worley3_q32;
use lps_builtins::builtins::lpfn::generative::worley::worley3_value_q32::__lp_lpfn_worley3_value_q32;

use util::snapshot::{assert_snapshot, finish_snapshot_update_if_requested, float_to_fixed};

const SNAPSHOT_HEADER: &str =
    "# Auto-generated by lpfn_q32_snapshots tests. Update by setting LP_UPDATE_SNAPSHOTS=1.\n";

fn sort_join(mut lines: Vec<String>) -> String {
    lines.sort();
    let mut s = String::from(SNAPSHOT_HEADER);
    for line in lines {
        s.push_str(&line);
        s.push('\n');
    }
    s
}

fn render_psrdnoise2_q32() -> String {
    let mut lines = Vec::new();
    let alphas = [float_to_fixed(0.0), float_to_fixed(0.5)];
    let seeds = [0u32, 42];
    let coords: &[(f32, f32)] = &[(1.5, 2.3), (-1.25, 3.75), (0.0, 0.0), (10.125, -0.5)];
    let periods: &[(f32, f32)] = &[(0.0, 0.0), (10.0, 10.0)];
    for &(x, y) in coords {
        for &(px, py) in periods {
            for &a in &alphas {
                for &seed in &seeds {
                    let xi = float_to_fixed(x);
                    let yi = float_to_fixed(y);
                    let pxi = float_to_fixed(px);
                    let pyi = float_to_fixed(py);
                    let mut g = [0i32; 2];
                    let n = __lp_lpfn_psrdnoise2_q32(xi, yi, pxi, pyi, a, g.as_mut_ptr(), seed);
                    lines.push(format!(
                        "psrdnoise2_q32(x={xi},y={yi},px={pxi},py={pyi},a={a},seed={seed}) = noise={n} grad=({},{})",
                        g[0], g[1]
                    ));
                }
            }
        }
    }
    sort_join(lines)
}

fn render_psrdnoise3_q32() -> String {
    let mut lines = Vec::new();
    let alphas = [float_to_fixed(0.0), float_to_fixed(0.5)];
    let seeds = [0u32, 7];
    let coords: &[(f32, f32, f32)] = &[
        (1.1, 2.2, 3.3),
        (-0.5, 4.0, 0.25),
        (0.0, 0.0, 0.0),
        (10.0, -3.0, 8.5),
    ];
    let periods: &[(f32, f32, f32)] = &[(0.0, 0.0, 0.0), (10.0, 10.0, 10.0)];
    for &(x, y, z) in coords {
        for &(px, py, pz) in periods {
            for &a in &alphas {
                for &seed in &seeds {
                    let xi = float_to_fixed(x);
                    let yi = float_to_fixed(y);
                    let zi = float_to_fixed(z);
                    let pxi = float_to_fixed(px);
                    let pyi = float_to_fixed(py);
                    let pzi = float_to_fixed(pz);
                    let mut g = [0i32; 3];
                    let n = __lp_lpfn_psrdnoise3_q32(
                        xi,
                        yi,
                        zi,
                        pxi,
                        pyi,
                        pzi,
                        a,
                        g.as_mut_ptr(),
                        seed,
                    );
                    lines.push(format!(
                        "psrdnoise3_q32(x={xi},y={yi},z={zi},px={pxi},py={pyi},pz={pzi},a={a},seed={seed}) = noise={n} grad=({},{},{})",
                        g[0], g[1], g[2]
                    ));
                }
            }
        }
    }
    sort_join(lines)
}

fn render_snoise2_q32() -> String {
    let mut lines = Vec::new();
    let seeds = [0u32, 1, 99, 12345];
    let coords: &[(f32, f32)] = &[
        (0.0, 0.0),
        (1.0, 2.0),
        (-3.5, 4.25),
        (12.125, -0.25),
        (100.0, -100.0),
        (0.1, 0.2),
        (7.7, 8.8),
        (3.14159, 2.71828),
    ];
    for &(x, y) in coords {
        for &seed in &seeds {
            let xi = float_to_fixed(x);
            let yi = float_to_fixed(y);
            let n = __lp_lpfn_snoise2_q32(xi, yi, seed);
            lines.push(format!("snoise2_q32(x={xi},y={yi},seed={seed}) = {n}"));
        }
    }
    sort_join(lines)
}

fn render_snoise3_q32() -> String {
    let mut lines = Vec::new();
    let seeds = [0u32, 3, 1001];
    let coords: &[(f32, f32, f32)] = &[
        (0.0, 0.0, 0.0),
        (1.0, 2.0, 3.0),
        (-1.0, 5.5, 0.125),
        (9.0, -9.0, 9.0),
        (33.0, 44.0, 55.0),
        (0.5, 0.25, 0.125),
        (6.0, 7.0, 8.0),
        (12.0, 3.0, 1.0),
        (2.2, 4.4, 6.6),
        (101.0, 102.0, 103.0),
    ];
    for &(x, y, z) in coords {
        for &seed in &seeds {
            let xi = float_to_fixed(x);
            let yi = float_to_fixed(y);
            let zi = float_to_fixed(z);
            let n = __lp_lpfn_snoise3_q32(xi, yi, zi, seed);
            lines.push(format!(
                "snoise3_q32(x={xi},y={yi},z={zi},seed={seed}) = {n}"
            ));
        }
    }
    sort_join(lines)
}

fn render_gnoise2_q32() -> String {
    let mut lines = Vec::new();
    let seeds = [0u32, 2, 404];
    let coords: &[(f32, f32)] = &[
        (0.0, 0.0),
        (0.5, 0.5),
        (-2.0, 3.0),
        (15.0, 16.0),
        (99.99, -0.01),
        (4.0, 5.0),
        (1.25, -7.5),
        (8.0, 8.0),
    ];
    for &(x, y) in coords {
        for &seed in &seeds {
            let xi = float_to_fixed(x);
            let yi = float_to_fixed(y);
            let n = __lp_lpfn_gnoise2_q32(xi, yi, seed);
            lines.push(format!("gnoise2_q32(x={xi},y={yi},seed={seed}) = {n}"));
        }
    }
    sort_join(lines)
}

fn render_gnoise3_q32() -> String {
    let mut lines = Vec::new();
    let seeds = [0u32, 11];
    let coords: &[(f32, f32, f32)] = &[
        (0.0, 0.0, 0.0),
        (1.0, 1.0, 1.0),
        (-4.0, 2.0, 9.0),
        (20.0, 21.0, 22.0),
        (0.1, 0.2, 0.3),
        (5.5, 6.6, 7.7),
        (13.0, 14.0, 15.0),
        (8.0, 1.0, 2.0),
    ];
    for &(x, y, z) in coords {
        for &seed in &seeds {
            let xi = float_to_fixed(x);
            let yi = float_to_fixed(y);
            let zi = float_to_fixed(z);
            let n = __lp_lpfn_gnoise3_q32(xi, yi, zi, seed);
            lines.push(format!(
                "gnoise3_q32(x={xi},y={yi},z={zi},seed={seed}) = {n}"
            ));
        }
    }
    sort_join(lines)
}

fn render_worley2_q32() -> String {
    let mut lines = Vec::new();
    let seeds = [0u32, 5, 9000];
    let coords: &[(f32, f32)] = &[
        (0.0, 0.0),
        (1.1, 2.2),
        (-5.0, 5.0),
        (3.33, 4.44),
        (12.0, 13.0),
        (0.25, 0.75),
        (50.0, -50.0),
        (7.0, 8.0),
    ];
    for &(x, y) in coords {
        for &seed in &seeds {
            let xi = float_to_fixed(x);
            let yi = float_to_fixed(y);
            let n = __lp_lpfn_worley2_q32(xi, yi, seed);
            lines.push(format!("worley2_q32(x={xi},y={yi},seed={seed}) = {n}"));
        }
    }
    sort_join(lines)
}

fn render_worley2_value_q32() -> String {
    let mut lines = Vec::new();
    let seeds = [0u32, 3];
    let coords: &[(f32, f32)] = &[
        (0.0, 0.0),
        (2.0, 3.0),
        (-1.0, 4.0),
        (10.0, 11.0),
        (0.125, 0.875),
        (22.0, 23.0),
        (6.5, 7.5),
        (40.0, 41.0),
        (9.0, 9.0),
        (1.5, 2.5),
        (30.0, 31.0),
        (4.0, 4.0),
        (8.25, 8.75),
        (15.0, 16.0),
        (17.0, 18.0),
        (19.0, 20.0),
    ];
    for &(x, y) in coords {
        for &seed in &seeds {
            let xi = float_to_fixed(x);
            let yi = float_to_fixed(y);
            let n = __lp_lpfn_worley2_value_q32(xi, yi, seed);
            lines.push(format!(
                "worley2_value_q32(x={xi},y={yi},seed={seed}) = {n}"
            ));
        }
    }
    sort_join(lines)
}

fn render_worley3_q32() -> String {
    let mut lines = Vec::new();
    let seeds = [0u32, 13];
    let coords: &[(f32, f32, f32)] = &[
        (0.0, 0.0, 0.0),
        (1.0, 2.0, 3.0),
        (-2.0, 4.0, 6.0),
        (5.0, 5.0, 5.0),
        (9.0, 8.0, 7.0),
        (0.5, 1.5, 2.5),
        (11.0, 12.0, 13.0),
        (20.0, 21.0, 22.0),
    ];
    for &(x, y, z) in coords {
        for &seed in &seeds {
            let xi = float_to_fixed(x);
            let yi = float_to_fixed(y);
            let zi = float_to_fixed(z);
            let n = __lp_lpfn_worley3_q32(xi, yi, zi, seed);
            lines.push(format!(
                "worley3_q32(x={xi},y={yi},z={zi},seed={seed}) = {n}"
            ));
        }
    }
    sort_join(lines)
}

fn render_worley3_value_q32() -> String {
    let mut lines = Vec::new();
    let seeds = [0u32, 1, 2];
    let coords: &[(f32, f32, f32)] = &[
        (0.0, 0.0, 0.0),
        (3.0, 4.0, 5.0),
        (-1.0, -2.0, -3.0),
        (10.0, 11.0, 12.0),
        (0.1, 0.2, 0.3),
        (6.0, 7.0, 8.0),
        (14.0, 15.0, 16.0),
        (17.0, 18.0, 19.0),
        (20.0, 21.0, 22.0),
        (23.0, 24.0, 25.0),
    ];
    for &(x, y, z) in coords {
        for &seed in &seeds {
            let xi = float_to_fixed(x);
            let yi = float_to_fixed(y);
            let zi = float_to_fixed(z);
            let n = __lp_lpfn_worley3_value_q32(xi, yi, zi, seed);
            lines.push(format!(
                "worley3_value_q32(x={xi},y={yi},z={zi},seed={seed}) = {n}"
            ));
        }
    }
    sort_join(lines)
}

fn render_fbm2_q32() -> String {
    let mut lines = Vec::new();
    let seeds = [0u32, 77];
    let octaves = [1i32, 2, 3, 4];
    let coords: &[(f32, f32)] = &[(0.0, 0.0), (1.0, 1.0), (-3.0, 4.0), (8.8, 9.9)];
    for &(x, y) in coords {
        for &o in &octaves {
            for &seed in &seeds {
                let xi = float_to_fixed(x);
                let yi = float_to_fixed(y);
                let n = __lp_lpfn_fbm2_q32(xi, yi, o, seed);
                lines.push(format!(
                    "fbm2_q32(x={xi},y={yi},octaves={o},seed={seed}) = {n}"
                ));
            }
        }
    }
    sort_join(lines)
}

fn render_fbm3_q32() -> String {
    let mut lines = Vec::new();
    let seeds = [0u32, 5];
    let octaves = [1i32, 2, 3, 4];
    let coords: &[(f32, f32, f32)] = &[
        (0.0, 0.0, 0.0),
        (2.0, 3.0, 4.0),
        (-1.0, 5.0, 9.0),
        (11.0, 12.0, 13.0),
    ];
    for &(x, y, z) in coords {
        for &o in &octaves {
            for &seed in &seeds {
                let xi = float_to_fixed(x);
                let yi = float_to_fixed(y);
                let zi = float_to_fixed(z);
                let n = __lp_lpfn_fbm3_q32(xi, yi, zi, o, seed);
                lines.push(format!(
                    "fbm3_q32(x={xi},y={yi},z={zi},octaves={o},seed={seed}) = {n}"
                ));
            }
        }
    }
    sort_join(lines)
}

fn render_hsv2rgb_q32() -> String {
    let mut lines = Vec::new();
    let triples: &[(f32, f32, f32)] = &[
        (0.0, 1.0, 1.0),
        (0.5, 1.0, 1.0),
        (0.25, 0.5, 0.75),
        (0.0, 0.0, 1.0),
        (1.0, 0.0, 0.5),
        (0.33, 0.8, 0.9),
        (0.66, 0.4, 0.3),
        (0.9, 0.2, 0.7),
        (0.1, 0.9, 0.1),
        (0.0, 0.5, 0.5),
        (0.45, 0.55, 0.65),
    ];
    for &(h, s, v) in triples {
        let hi = float_to_fixed(h);
        let si = float_to_fixed(s);
        let vi = float_to_fixed(v);
        let mut out = [0i32; 3];
        __lp_lpfn_hsv2rgb_q32(out.as_mut_ptr(), hi, si, vi);
        lines.push(format!(
            "hsv2rgb_q32(h={hi},s={si},v={vi}) = ({},{},{})",
            out[0], out[1], out[2]
        ));
    }
    sort_join(lines)
}

fn render_sincos_q32() -> String {
    let mut lines = Vec::new();
    let angles: &[f32] = &[
        -6.2831855, -3.1415927, -1.5707963, -0.7853982, -0.1, 0.0, 0.1, 0.25, 0.5, 0.7853982, 1.0,
        1.5707963, 2.0, 2.5, 3.1415927, 3.5, 4.0, 4.712389, 5.0, 5.5, 6.0, 6.2831855, 7.0, 10.0,
    ];
    for &a in angles {
        let x = float_to_fixed(a);
        let (s, c) = lps_sincos_q32_pair(x);
        lines.push(format!("sincos_q32(x={x}) = sin={s} cos={c}"));
    }
    sort_join(lines)
}

fn render_rgb2hsv_q32() -> String {
    let mut lines = Vec::new();
    let triples: &[(f32, f32, f32)] = &[
        (1.0, 0.0, 0.0),
        (0.0, 1.0, 0.0),
        (0.0, 0.0, 1.0),
        (1.0, 1.0, 1.0),
        (0.5, 0.5, 0.5),
        (0.2, 0.4, 0.6),
        (0.9, 0.1, 0.2),
        (0.0, 0.0, 0.0),
        (0.33, 0.66, 0.99),
        (0.25, 0.75, 0.25),
        (0.8, 0.2, 0.3),
    ];
    for &(r, g, b) in triples {
        let ri = float_to_fixed(r);
        let gi = float_to_fixed(g);
        let bi = float_to_fixed(b);
        let mut out = [0i32; 3];
        __lp_lpfn_rgb2hsv_q32(out.as_mut_ptr(), ri, gi, bi);
        lines.push(format!(
            "rgb2hsv_q32(r={ri},g={gi},b={bi}) = ({},{},{})",
            out[0], out[1], out[2]
        ));
    }
    sort_join(lines)
}

#[test]
fn lpfn_q32_snapshots() {
    assert_snapshot("psrdnoise2_q32", &render_psrdnoise2_q32());
    assert_snapshot("psrdnoise3_q32", &render_psrdnoise3_q32());
    assert_snapshot("snoise2_q32", &render_snoise2_q32());
    assert_snapshot("snoise3_q32", &render_snoise3_q32());
    assert_snapshot("gnoise2_q32", &render_gnoise2_q32());
    assert_snapshot("gnoise3_q32", &render_gnoise3_q32());
    assert_snapshot("worley2_q32", &render_worley2_q32());
    assert_snapshot("worley2_value_q32", &render_worley2_value_q32());
    assert_snapshot("worley3_q32", &render_worley3_q32());
    assert_snapshot("worley3_value_q32", &render_worley3_value_q32());
    assert_snapshot("fbm2_q32", &render_fbm2_q32());
    assert_snapshot("fbm3_q32", &render_fbm3_q32());
    assert_snapshot("hsv2rgb_q32", &render_hsv2rgb_q32());
    assert_snapshot("rgb2hsv_q32", &render_rgb2hsv_q32());
    assert_snapshot("sincos_q32", &render_sincos_q32());
    finish_snapshot_update_if_requested();
}
