use crate::model::StaticSlotRecord;

pub(crate) fn render_slot_codecs(records: &[StaticSlotRecord]) -> String {
    let mut out = String::from("// @generated by lpc-slot-codegen. Do not edit.\n\n");
    out.push_str(SLOT_CODEC_IMPORTS);
    for record in records {
        render_slot_codec_record_impl(&mut out, record);
    }
    out
}

fn render_slot_codec_record_impl(out: &mut String, record: &StaticSlotRecord) {
    let stem = slot_codec_record_stem(&record.type_name);
    render_slot_codec_record_read_body(out, record, &stem);
    render_slot_codec_record_write_body(out, record, &stem);

    out.push_str("impl SlotCodec for ");
    out.push_str(&record.type_path);
    out.push_str(" {\n");
    out.push_str(
        "    fn read_slot<S>(value: ValueReader<'_, '_, S>) -> Result<Self, SyntaxError>\n",
    );
    out.push_str("    where\n        S: SyntaxEventSource,\n    {\n");
    out.push_str("        read_");
    out.push_str(&stem);
    out.push_str("_slot_body(value.object()?)\n");
    out.push_str("    }\n\n");

    out.push_str(
        "    fn write_slot<W>(&self, value: SlotValueWriter<'_, W>) -> Result<(), SlotWriteError<W::Error>>\n",
    );
    out.push_str("    where\n        W: SlotWrite,\n    {\n");
    out.push_str("        let mut object = value.object()?;\n");
    out.push_str("        write_");
    out.push_str(&stem);
    out.push_str("_slot_body(&mut object, self)?;\n");
    out.push_str("        object.finish()\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

fn render_slot_codec_record_read_body(out: &mut String, record: &StaticSlotRecord, stem: &str) {
    out.push_str("pub(crate) fn read_");
    out.push_str(stem);
    out.push_str("_slot_body<S>(mut object: ObjectReader<'_, '_, S>) -> Result<");
    out.push_str(&record.type_path);
    out.push_str(", SyntaxError>\nwhere\n    S: SyntaxEventSource,\n{\n");
    render_slot_codec_record_fields_const(out, record, "    ");
    out.push_str("    let mut out = <");
    out.push_str(&record.type_path);
    out.push_str(" as Default>::default();\n");
    out.push_str("    while let Some(mut prop) = object.next_prop()? {\n");
    out.push_str("        match prop.name() {\n");
    for field in &record.fields {
        out.push_str("            \"");
        out.push_str(&field.slot_name);
        out.push_str("\" => ");
        out.push_str("out.");
        out.push_str(&field.rust_name);
        out.push_str(" = SlotCodec::read_slot(prop.value())?,\n");
    }
    out.push_str("            other => return Err(prop.unknown_field(other, FIELDS)),\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    Ok(out)\n");
    out.push_str("}\n\n");
}

fn render_slot_codec_record_write_body(out: &mut String, record: &StaticSlotRecord, stem: &str) {
    out.push_str("pub(crate) fn write_");
    out.push_str(stem);
    out.push_str("_slot_body<W>(object: &mut SlotObjectWriter<'_, W>, value: &");
    out.push_str(&record.type_path);
    out.push_str(") -> Result<(), SlotWriteError<W::Error>>\nwhere\n    W: SlotWrite,\n{\n");
    for field in record.fields.iter() {
        out.push_str("    if value.");
        out.push_str(&field.rust_name);
        out.push_str(".should_write_slot() {\n");
        out.push_str("        value.");
        out.push_str(&field.rust_name);
        out.push_str(".write_slot(object.prop(\"");
        out.push_str(&field.slot_name);
        out.push_str("\")?)?;\n");
        out.push_str("    }\n");
    }
    out.push_str("    Ok(())\n");
    out.push_str("}\n\n");
}

fn slot_codec_record_stem(type_name: &str) -> String {
    let mut stem = String::new();
    for (index, ch) in type_name.chars().enumerate() {
        if ch.is_uppercase() {
            if index != 0 {
                stem.push('_');
            }
            stem.extend(ch.to_lowercase());
        } else {
            stem.push(ch);
        }
    }
    stem
}

fn render_slot_codec_record_fields_const(
    out: &mut String,
    record: &StaticSlotRecord,
    indent: &str,
) {
    out.push_str(indent);
    out.push_str("const FIELDS: &[&str] = &[");
    for (index, field) in record.fields.iter().enumerate() {
        if index != 0 {
            out.push_str(", ");
        }
        out.push('"');
        out.push_str(&field.slot_name);
        out.push('"');
    }
    out.push_str("];\n");
}

const SLOT_CODEC_IMPORTS: &str = r#"
use lpc_model::slot_codec::{
    ObjectReader, SlotCodec, SlotObjectWriter, SlotValueWriter, SlotWrite, SlotWriteError,
    SyntaxError, SyntaxEventSource, ValueReader,
};

"#;
