use crate::model::StaticSlotView;

pub(crate) fn render_slot_views(views: &[StaticSlotView]) -> String {
    let mut out = String::from("// @generated by lpc-slot-codegen. Do not edit.\n\n");
    for view in views {
        render_one_slot_view(&mut out, view);
    }
    out
}

fn render_one_slot_view(out: &mut String, view: &StaticSlotView) {
    out.push_str("pub struct ");
    out.push_str(&view.view_name);
    out.push_str(" {\n");
    out.push_str("    registry_revision: ::lpc_model::Revision,\n");
    for field in &view.fields {
        out.push_str("    ");
        out.push_str(&field.accessor_name);
        out.push_str(": ::lpc_model::SlotAccessor,\n");
        if let Some(some_accessor_name) = &field.some_accessor_name {
            out.push_str("    ");
            out.push_str(some_accessor_name);
            out.push_str(": ::lpc_model::SlotAccessor,\n");
        }
    }
    out.push_str("}\n\n");

    out.push_str("impl ");
    out.push_str(&view.view_name);
    out.push_str(" {\n");
    out.push_str("    pub fn compile(\n");
    out.push_str("        registry: &(impl ::lpc_model::SlotShapeLookup + ?Sized),\n");
    out.push_str("    ) -> Result<Self, ::lpc_model::SlotAccessorError> {\n");
    out.push_str("        Ok(Self {\n");
    out.push_str("            registry_revision: registry.revision(),\n");
    for field in &view.fields {
        out.push_str("            ");
        out.push_str(&field.accessor_name);
        out.push_str(": ::lpc_model::SlotAccessor::compile(\n");
        out.push_str("                <");
        out.push_str(&view.type_path);
        out.push_str(" as ::lpc_model::StaticSlotShape>::SHAPE_ID,\n");
        out.push_str("                ::lpc_model::SlotPath::parse(\"");
        out.push_str(&super::rust_string::escape_rust_string(&field.slot_name));
        out.push_str("\").expect(\"generated slot field path is valid\"),\n");
        out.push_str("                registry,\n");
        out.push_str("            )?,\n");
        if let Some(some_accessor_name) = &field.some_accessor_name {
            out.push_str("            ");
            out.push_str(some_accessor_name);
            out.push_str(": ::lpc_model::SlotAccessor::compile(\n");
            out.push_str("                <");
            out.push_str(&view.type_path);
            out.push_str(" as ::lpc_model::StaticSlotShape>::SHAPE_ID,\n");
            out.push_str("                ::lpc_model::SlotPath::parse(\"");
            out.push_str(&super::rust_string::escape_rust_string(&field.slot_name));
            out.push_str(".some\").expect(\"generated option slot payload path is valid\"),\n");
            out.push_str("                registry,\n");
            out.push_str("            )?,\n");
        }
    }
    out.push_str("        })\n");
    out.push_str("    }\n\n");

    out.push_str("    pub fn get_or_compile<'a>(\n");
    out.push_str("        cache: &'a mut Option<Self>,\n");
    out.push_str("        registry: &(impl ::lpc_model::SlotShapeLookup + ?Sized),\n");
    out.push_str("    ) -> Result<&'a Self, ::lpc_model::SlotAccessorError> {\n");
    out.push_str("        let needs_compile = cache\n");
    out.push_str("            .as_ref()\n");
    out.push_str("            .is_none_or(|view| !view.is_valid_for(registry));\n");
    out.push_str("        if needs_compile {\n");
    out.push_str("            *cache = Some(Self::compile(registry)?);\n");
    out.push_str("        }\n");
    out.push_str("        Ok(cache.as_ref().expect(\"slot view cache was just compiled\"))\n");
    out.push_str("    }\n\n");

    out.push_str("    pub fn registry_revision(&self) -> ::lpc_model::Revision {\n");
    out.push_str("        self.registry_revision\n");
    out.push_str("    }\n\n");

    out.push_str("    pub fn is_valid_for(\n");
    out.push_str("        &self,\n");
    out.push_str("        registry: &(impl ::lpc_model::SlotShapeLookup + ?Sized),\n");
    out.push_str("    ) -> bool {\n");
    out.push_str("        self.registry_revision == registry.revision()\n");
    out.push_str("    }\n\n");

    for field in &view.fields {
        out.push_str("    pub fn ");
        out.push_str(&field.method_name);
        if let Some(some_accessor_name) = &field.some_accessor_name {
            out.push_str("(&self) -> ::lpc_model::SlotOptionReader<'_> {\n");
            out.push_str("        ::lpc_model::SlotOptionReader::new(&self.");
            out.push_str(&field.accessor_name);
            out.push_str(", &self.");
            out.push_str(some_accessor_name);
            out.push_str(")\n");
        } else {
            out.push_str("(&self) -> ::lpc_model::SlotFieldReader<'_> {\n");
            out.push_str("        ::lpc_model::SlotFieldReader::new(&self.");
            out.push_str(&field.accessor_name);
            out.push_str(")\n");
        }
        out.push_str("    }\n\n");
    }

    out.push_str("}\n\n");
}
