use crate::model::StaticRegisteredShape;

pub(crate) fn render_slot_shapes(shapes: &[StaticRegisteredShape]) -> String {
    let mut out = String::from("// @generated by lpc-slot-codegen. Do not edit.\n\n");
    render_static_catalog(shapes, &mut out);
    out.push_str("pub fn register_all_static_slot_shapes(\n");
    if shapes.is_empty() {
        out.push_str("    _registry: &mut ::lpc_model::SlotShapeRegistry,\n");
    } else {
        out.push_str("    registry: &mut ::lpc_model::SlotShapeRegistry,\n");
    }
    out.push_str(") -> Result<(), ::lpc_model::SlotShapeRegistryError> {\n");
    for shape in shapes {
        out.push_str("    ensure_static_slot_shape(registry, <");
        out.push_str(&shape.type_path);
        out.push_str(" as ::lpc_model::StaticSlotShape>::SHAPE_ID)?;\n");
    }
    out.push_str("    Ok(())\n");
    out.push_str("}\n\n");

    out.push_str("pub fn ensure_static_slot_shape(\n");
    if shapes.is_empty() {
        out.push_str("    _registry: &mut ::lpc_model::SlotShapeRegistry,\n");
        out.push_str("    _id: ::lpc_model::SlotShapeId,\n");
    } else {
        out.push_str("    registry: &mut ::lpc_model::SlotShapeRegistry,\n");
        out.push_str("    id: ::lpc_model::SlotShapeId,\n");
    }
    out.push_str(") -> Result<bool, ::lpc_model::SlotShapeRegistryError> {\n");
    for (index, shape) in shapes.iter().enumerate() {
        if index == 0 {
            out.push_str("    if id == <");
        } else {
            out.push_str("    } else if id == <");
        }
        out.push_str(&shape.type_path);
        out.push_str(" as ::lpc_model::StaticSlotShape>::SHAPE_ID {\n");
        if shape.has_default_factory {
            out.push_str("        let inserted = <");
            out.push_str(&shape.type_path);
            out.push_str(" as ::lpc_model::StaticSlotShape>::ensure_registered_with_factory(\n");
            out.push_str("            registry,\n");
            out.push_str("            ::lpc_model::SlotFactory::for_default::<");
            out.push_str(&shape.type_path);
            out.push_str(">(),\n");
            out.push_str("        )?;\n");
        } else {
            out.push_str("        let inserted = <");
            out.push_str(&shape.type_path);
            out.push_str(" as ::lpc_model::StaticSlotShape>::ensure_registered(registry)?;\n");
        }
        out.push_str("        ensure_referenced_static_slot_shapes(registry, id)?;\n");
        out.push_str("        Ok(inserted)\n");
    }
    if shapes.is_empty() {
        out.push_str("    Ok(false)\n");
    } else {
        out.push_str("    } else {\n");
        out.push_str("        Ok(false)\n");
        out.push_str("    }\n");
    }
    out.push_str("}\n");

    if !shapes.is_empty() {
        out.push_str("\nfn ensure_referenced_static_slot_shapes(\n");
        out.push_str("    registry: &mut ::lpc_model::SlotShapeRegistry,\n");
        out.push_str("    id: ::lpc_model::SlotShapeId,\n");
        out.push_str(") -> Result<(), ::lpc_model::SlotShapeRegistryError> {\n");
        out.push_str("    let refs = registry\n");
        out.push_str("        .get(&id)\n");
        out.push_str("        .map(::lpc_model::SlotShape::referenced_shape_ids)\n");
        out.push_str("        .unwrap_or_default();\n");
        out.push_str("    for ref_id in refs {\n");
        out.push_str("        if registry.contains(&ref_id) {\n");
        out.push_str("            continue;\n");
        out.push_str("        }\n");
        out.push_str("        if !ensure_static_slot_shape(registry, ref_id)? {\n");
        out.push_str("            return Err(::lpc_model::SlotShapeRegistryError::MissingReferencedShape(ref_id));\n");
        out.push_str("        }\n");
        out.push_str("    }\n");
        out.push_str("    Ok(())\n");
        out.push_str("}\n");
    }

    out
}

fn render_static_catalog(shapes: &[StaticRegisteredShape], out: &mut String) {
    out.push_str("pub fn static_slot_shape_ids() -> &'static [::lpc_model::SlotShapeId] {\n");
    if shapes.is_empty() {
        out.push_str("    &[]\n");
    } else {
        out.push_str("    static IDS: [::lpc_model::SlotShapeId; ");
        out.push_str(&shapes.len().to_string());
        out.push_str("] = [\n");
        for shape in shapes {
            out.push_str("        <");
            out.push_str(&shape.type_path);
            out.push_str(" as ::lpc_model::StaticSlotShape>::SHAPE_ID,\n");
        }
        out.push_str("    ];\n");
        out.push_str("    &IDS\n");
    }
    out.push_str("}\n\n");

    out.push_str("pub fn static_slot_shape(\n");
    out.push_str("    id: ::lpc_model::SlotShapeId,\n");
    out.push_str(") -> Option<&'static ::lpc_model::StaticSlotShapeDescriptor> {\n");
    render_shape_match(shapes, out, |shape, out| {
        out.push_str("        <");
        out.push_str(&shape.type_path);
        out.push_str(" as ::lpc_model::StaticSlotShape>::static_slot_shape_descriptor()\n");
    });
    out.push_str("}\n\n");

    out.push_str(
        "pub fn static_slot_shape_name(id: ::lpc_model::SlotShapeId) -> Option<&'static str> {\n",
    );
    render_shape_match(shapes, out, |shape, out| {
        out.push_str("        <");
        out.push_str(&shape.type_path);
        out.push_str(" as ::lpc_model::StaticSlotShape>::shape_name()\n");
    });
    out.push_str("}\n\n");

    out.push_str("pub fn create_static_slot_default(\n");
    out.push_str("    id: ::lpc_model::SlotShapeId,\n");
    out.push_str(") -> Option<::lpc_model::SlotFactory> {\n");
    render_shape_match(shapes, out, |shape, out| {
        if shape.has_default_factory {
            out.push_str("        Some(::lpc_model::SlotFactory::for_default::<");
            out.push_str(&shape.type_path);
            out.push_str(">())\n");
        } else {
            out.push_str("        Some(::lpc_model::SlotFactory::unsupported())\n");
        }
    });
    out.push_str("}\n\n");
}

fn render_shape_match<F>(shapes: &[StaticRegisteredShape], out: &mut String, mut arm: F)
where
    F: FnMut(&StaticRegisteredShape, &mut String),
{
    for (index, shape) in shapes.iter().enumerate() {
        if index == 0 {
            out.push_str("    if id == <");
        } else {
            out.push_str("    } else if id == <");
        }
        out.push_str(&shape.type_path);
        out.push_str(" as ::lpc_model::StaticSlotShape>::SHAPE_ID {\n");
        arm(shape, out);
    }
    if shapes.is_empty() {
        out.push_str("    None\n");
    } else {
        out.push_str("    } else {\n");
        out.push_str("        None\n");
        out.push_str("    }\n");
    }
}
