kind = "Shader"
source = { path = "attract.glsl" }
render_order = 0

[glsl_opts]
add_sub = "wrapping"
mul = "wrapping"
div = "reciprocal"

[consumed.time]
kind = "value"
value = "f32"
default = 0.0

[consumed.speed]
kind = "value"
value = "f32"
default = 2
min = 0.0
max = 3.0
label = "Speed"
description = "Attract wheel rotation speed multiplier"
