kind = "Shader"
source = { path = "blast.glsl" }
render_order = 0

[bindings.time]
source = "..#entry_time"

[bindings.progress]
source = "..#entry_progress"

[glsl_opts]
add_sub = "wrapping"
mul = "wrapping"
div = "reciprocal"

[consumed.time]
kind = "value"
value = "f32"
default = 0.0

[consumed.progress]
kind = "value"
value = "f32"
default = 0.0
