kind = "ComputeShader"
glsl_path = "event_b.glsl"

[bindings.events]
target = "bus#trigger"

[bindings.time]
source = "bus#time.seconds"

[consumed_slots.time]
kind = "value"
value = "f32"
default = 0.0

[produced_slots.events]
kind = "map"
key = "u32"
value = "lp::control::Message"
mapping = { kind = "sentinel", len = 8, key = "id", empty_key = 0 }
