kind = "Project"
name = "events"

[nodes.output]
ref = "./output.toml"

[nodes.clock]
ref = "./clock.toml"

[nodes.event_a]
ref = "./event_a.toml"

[nodes.event_b]
ref = "./event_b.toml"

[nodes.shader]
ref = "./shader.toml"

[nodes.fixture]
ref = "./fixture.toml"
