//! 32-bit fixed-point transform
//!
//! Converts the floating-point instructions generated by the compiler to
//! 16.16 fixed-point instructions for use on hardware without floating-point support
//! such as the riscv32imac cores on the esp32c3 and esp32c6

mod converters;
mod instructions;
mod options;
mod signature;
mod transform;
mod types;

#[cfg(test)]
mod q32_test_util;

pub use options::Q32Options;
pub use transform::Q32Transform;
pub use types::FixedPointFormat;
