//! WASM valtypes for each `BuiltinId` import (wasm32, `extern "C"` layout).
//!
//! AUTO-GENERATED by lps-builtins-gen-app. Do not edit manually.
//!
//! Regenerate: `cargo run -p lps-builtins-gen-app` or `scripts/build-builtins.sh`

extern crate alloc;

use alloc::vec;
use alloc::vec::Vec;
use lps_builtin_ids::BuiltinId;
use wasm_encoder::ValType;

/// Parameter and result WASM types for the imported builtin function.
pub(super) fn wasm_import_val_types(builtin: BuiltinId) -> (Vec<ValType>, Vec<ValType>) {
    match builtin {
        BuiltinId::LpGlslAcosQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslAcoshQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslAsinQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslAsinhQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslAtan2Q32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslAtanQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslAtanhQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslCosQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslCoshQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslExp2Q32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslExpQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslFmaQ32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpGlslInversesqrtQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslLdexpQ32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslLog2Q32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslLogQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslModQ32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslPowQ32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslRoundQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslSinQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslSinhQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslTanQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslTanhQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFaddQ32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFdivQ32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFmulQ32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFnearestQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFsqrtQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFsubQ32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpfxFbm2F32 => (
            vec![ValType::F32, ValType::F32, ValType::I32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfxFbm2Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfxFbm3F32 => (
            vec![
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfxFbm3Q32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfxFbm3TileF32 => (
            vec![
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfxFbm3TileQ32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfxGnoise1F32 => (vec![ValType::F32, ValType::I32], vec![ValType::F32]),
        BuiltinId::LpLpfxGnoise1Q32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpfxGnoise2F32 => (
            vec![ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfxGnoise2Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfxGnoise3F32 => (
            vec![ValType::F32, ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfxGnoise3Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfxGnoise3TileF32 => (
            vec![
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
            ],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfxGnoise3TileQ32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfxHash1 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpfxHash2 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfxHash3 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfxHsv2rgbF32 => (
            vec![ValType::I32, ValType::F32, ValType::F32, ValType::F32],
            Vec::new(),
        ),
        BuiltinId::LpLpfxHsv2rgbQ32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            Vec::new(),
        ),
        BuiltinId::LpLpfxHsv2rgbVec4F32 => (
            vec![
                ValType::I32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfxHsv2rgbVec4Q32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfxHue2rgbF32 => (vec![ValType::I32, ValType::F32], Vec::new()),
        BuiltinId::LpLpfxHue2rgbQ32 => (vec![ValType::I32, ValType::I32], Vec::new()),
        BuiltinId::LpLpfxPsrdnoise2F32 => (
            vec![
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfxPsrdnoise2Q32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfxPsrdnoise3F32 => (
            vec![
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfxPsrdnoise3Q32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfxRandom1F32 => (vec![ValType::F32, ValType::I32], vec![ValType::F32]),
        BuiltinId::LpLpfxRandom1Q32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpfxRandom2F32 => (
            vec![ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfxRandom2Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfxRandom3F32 => (
            vec![ValType::F32, ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfxRandom3Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfxRgb2hsvF32 => (
            vec![ValType::I32, ValType::F32, ValType::F32, ValType::F32],
            Vec::new(),
        ),
        BuiltinId::LpLpfxRgb2hsvQ32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            Vec::new(),
        ),
        BuiltinId::LpLpfxRgb2hsvVec4F32 => (
            vec![
                ValType::I32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfxRgb2hsvVec4Q32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfxSaturateF32 => (vec![ValType::F32], vec![ValType::F32]),
        BuiltinId::LpLpfxSaturateQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpfxSaturateVec3F32 => (
            vec![ValType::I32, ValType::F32, ValType::F32, ValType::F32],
            Vec::new(),
        ),
        BuiltinId::LpLpfxSaturateVec3Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            Vec::new(),
        ),
        BuiltinId::LpLpfxSaturateVec4F32 => (
            vec![
                ValType::I32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfxSaturateVec4Q32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfxSnoise1F32 => (vec![ValType::F32, ValType::I32], vec![ValType::F32]),
        BuiltinId::LpLpfxSnoise1Q32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpfxSnoise2F32 => (
            vec![ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfxSnoise2Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfxSnoise3F32 => (
            vec![ValType::F32, ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfxSnoise3Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfxSrandom1F32 => (vec![ValType::F32, ValType::I32], vec![ValType::F32]),
        BuiltinId::LpLpfxSrandom1Q32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpfxSrandom2F32 => (
            vec![ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfxSrandom2Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfxSrandom3F32 => (
            vec![ValType::F32, ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfxSrandom3Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfxSrandom3TileF32 => (
            vec![
                ValType::I32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfxSrandom3TileQ32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfxSrandom3VecF32 => (
            vec![
                ValType::I32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfxSrandom3VecQ32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfxWorley2F32 => (
            vec![ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfxWorley2Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfxWorley2ValueF32 => (
            vec![ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfxWorley2ValueQ32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfxWorley3F32 => (
            vec![ValType::F32, ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfxWorley3Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfxWorley3ValueF32 => (
            vec![ValType::F32, ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfxWorley3ValueQ32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpVmGetFuelQ32 => (vec![ValType::I32], vec![ValType::I32]),
    }
}
