//! WASM valtypes for each `BuiltinId` import (wasm32, `extern "C"` layout).
//!
//! AUTO-GENERATED by lps-builtins-gen-app. Do not edit manually.
//!
//! Regenerate: `cargo run -p lps-builtins-gen-app` or `scripts/build-builtins.sh`

extern crate alloc;

use alloc::vec;
use alloc::vec::Vec;
use lps_builtin_ids::BuiltinId;
use wasm_encoder::ValType;

/// Parameter and result WASM types for the imported builtin function.
pub(super) fn wasm_import_val_types(builtin: BuiltinId) -> (Vec<ValType>, Vec<ValType>) {
    match builtin {
        BuiltinId::LpGlslAcosQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslAcoshQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslAsinQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslAsinhQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslAtan2Q32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslAtanQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslAtanhQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslCosQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslCoshQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslExp2Q32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslExpQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslFmaQ32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpGlslInversesqrtQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslLdexpQ32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslLog2Q32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslLogQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslModQ32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslPowQ32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslRoundQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslSinQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslSinhQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslTanQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpGlslTanhQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFabsQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFaddQ32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFceilQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFdivQ32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFfloorQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFmaxQ32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFminQ32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFmulQ32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFnearestQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFsqrtQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFsubQ32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFtoUnorm16Q32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFtoUnorm8Q32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFtoiSatSQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFtoiSatUQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirFtruncQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirItofSQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirItofUQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirUnorm16ToFQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpirUnorm8ToFQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpfnFbm2F32 => (
            vec![ValType::F32, ValType::F32, ValType::I32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfnFbm2Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfnFbm3F32 => (
            vec![
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfnFbm3Q32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfnFbm3TileF32 => (
            vec![
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfnFbm3TileQ32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfnGnoise1F32 => (vec![ValType::F32, ValType::I32], vec![ValType::F32]),
        BuiltinId::LpLpfnGnoise1Q32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpfnGnoise2F32 => (
            vec![ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfnGnoise2Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfnGnoise3F32 => (
            vec![ValType::F32, ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfnGnoise3Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfnGnoise3TileF32 => (
            vec![
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
            ],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfnGnoise3TileQ32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfnHash1 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpfnHash2 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfnHash3 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfnHsv2rgbF32 => (
            vec![ValType::I32, ValType::F32, ValType::F32, ValType::F32],
            Vec::new(),
        ),
        BuiltinId::LpLpfnHsv2rgbQ32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            Vec::new(),
        ),
        BuiltinId::LpLpfnHsv2rgbVec4F32 => (
            vec![
                ValType::I32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfnHsv2rgbVec4Q32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfnHue2rgbF32 => (vec![ValType::I32, ValType::F32], Vec::new()),
        BuiltinId::LpLpfnHue2rgbQ32 => (vec![ValType::I32, ValType::I32], Vec::new()),
        BuiltinId::LpLpfnPsrdnoise2F32 => (
            vec![
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfnPsrdnoise2Q32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfnPsrdnoise3F32 => (
            vec![
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfnPsrdnoise3Q32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfnRandom1F32 => (vec![ValType::F32, ValType::I32], vec![ValType::F32]),
        BuiltinId::LpLpfnRandom1Q32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpfnRandom2F32 => (
            vec![ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfnRandom2Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfnRandom3F32 => (
            vec![ValType::F32, ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfnRandom3Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfnRgb2hsvF32 => (
            vec![ValType::I32, ValType::F32, ValType::F32, ValType::F32],
            Vec::new(),
        ),
        BuiltinId::LpLpfnRgb2hsvQ32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            Vec::new(),
        ),
        BuiltinId::LpLpfnRgb2hsvVec4F32 => (
            vec![
                ValType::I32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfnRgb2hsvVec4Q32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfnSaturateF32 => (vec![ValType::F32], vec![ValType::F32]),
        BuiltinId::LpLpfnSaturateQ32 => (vec![ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpfnSaturateVec3F32 => (
            vec![ValType::I32, ValType::F32, ValType::F32, ValType::F32],
            Vec::new(),
        ),
        BuiltinId::LpLpfnSaturateVec3Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            Vec::new(),
        ),
        BuiltinId::LpLpfnSaturateVec4F32 => (
            vec![
                ValType::I32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfnSaturateVec4Q32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfnSnoise1F32 => (vec![ValType::F32, ValType::I32], vec![ValType::F32]),
        BuiltinId::LpLpfnSnoise1Q32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpfnSnoise2F32 => (
            vec![ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfnSnoise2Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfnSnoise3F32 => (
            vec![ValType::F32, ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfnSnoise3Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfnSrandom1F32 => (vec![ValType::F32, ValType::I32], vec![ValType::F32]),
        BuiltinId::LpLpfnSrandom1Q32 => (vec![ValType::I32, ValType::I32], vec![ValType::I32]),
        BuiltinId::LpLpfnSrandom2F32 => (
            vec![ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfnSrandom2Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfnSrandom3F32 => (
            vec![ValType::F32, ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfnSrandom3Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfnSrandom3TileF32 => (
            vec![
                ValType::I32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfnSrandom3TileQ32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfnSrandom3VecF32 => (
            vec![
                ValType::I32,
                ValType::F32,
                ValType::F32,
                ValType::F32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfnSrandom3VecQ32 => (
            vec![
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
                ValType::I32,
            ],
            Vec::new(),
        ),
        BuiltinId::LpLpfnWorley2F32 => (
            vec![ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfnWorley2Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfnWorley2ValueF32 => (
            vec![ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfnWorley2ValueQ32 => (
            vec![ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfnWorley3F32 => (
            vec![ValType::F32, ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfnWorley3Q32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpLpfnWorley3ValueF32 => (
            vec![ValType::F32, ValType::F32, ValType::F32, ValType::I32],
            vec![ValType::F32],
        ),
        BuiltinId::LpLpfnWorley3ValueQ32 => (
            vec![ValType::I32, ValType::I32, ValType::I32, ValType::I32],
            vec![ValType::I32],
        ),
        BuiltinId::LpVmGetFuelQ32 => (vec![ValType::I32], vec![ValType::I32]),
    }
}
