//! Emit `lps-builtin-completions/src/lib.rs`: the GLSL editor completion manifest.
//!
//! Completions are generated from the compiler's builtin sources so the editor
//! can never drift from what the compiler accepts (roadmap D5: never
//! hand-author completion data).
//!
//! - **LPFN** entries carry the full typed GLSL signature (from the
//!   `#[lpfn_impl]` attribute), a snippet built from the parsed parameter
//!   names, and a description taken from the extern fn's doc comment.
//! - **glsl** entries come from two compiler sources: the runtime-import
//!   `(name, arg_count)` mapping-table keys (sin/cos/pow/…) and the
//!   inlined-builtin inventory `lps_glsl::builtin_inventory` (mix/clamp/
//!   dot/… — no `BuiltinId`, lowered directly to LPIR). Name + arity
//!   snippets only (no hand-authored type detail).
//! - **texture** entries mirror the texture mapping-table keys.
//! - **lpir / vm** builtins are IR/VM internals, not callable from user
//!   GLSL — deliberately absent.

use std::fs;
use std::path::Path;

use crate::BuiltinInfo;
use crate::discovery::discover_lpfn_functions;
use crate::lpfn::errors::Variant;
use crate::lpfn::grouping::{group_by_signature, group_functions_by_name};
use crate::lpfn::process::process_lpfn_functions;
use crate::lpfn::validate::{ParsedLpfnFunction, validate_lpfn_functions};
use crate::q32_glsl_import_keys;

/// One completion entry, pre-render.
struct Entry {
    name: String,
    module: &'static str,
    detail: String,
    snippet: String,
    description: String,
}

/// Generate `lps-builtin-completions/src/lib.rs` from builtin metadata.
pub(crate) fn generate_builtin_completions(
    path: &Path,
    builtins: &[BuiltinInfo],
    lpfn_dir: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let discovered = discover_lpfn_functions(lpfn_dir)?;
    let parsed = process_lpfn_functions(&discovered)?;
    validate_lpfn_functions(&parsed)?;

    let mut entries = lpfn_entries(&parsed);
    entries.extend(table_entries(builtins));
    entries.extend(inlined_entries());

    entries.sort_by(|a, b| {
        (a.name.as_str(), a.module, a.detail.as_str()).cmp(&(
            b.name.as_str(),
            b.module,
            b.detail.as_str(),
        ))
    });
    entries.dedup_by(|a, b| a.name == b.name && a.module == b.module && a.detail == b.detail);

    let mut out = String::from(HEADER);
    for entry in &entries {
        out.push_str(&format!(
            "    CompletionEntry {{\n        name: \"{}\",\n        module: \"{}\",\n        detail: \"{}\",\n        snippet: \"{}\",\n        description: \"{}\",\n    }},\n",
            escape(&entry.name),
            escape(entry.module),
            escape(&entry.detail),
            escape(&entry.snippet),
            escape(&entry.description),
        ));
    }
    out.push_str("];\n");

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, out)?;
    Ok(())
}

const HEADER: &str = r#"//! GLSL editor completion manifest for LightPlayer shader builtins.
//!
//! This file is AUTO-GENERATED by lps-builtins-gen-app. Do not edit manually.
//!
//! To regenerate: `cargo run -p lps-builtins-gen-app`
//!
//! Or use the build script:
//!     scripts/build-builtins.sh
//!
//! Entries are generated from the compiler's builtin sources
//! (`lps-builtins/src/builtins/*`); never hand-author completion data here
//! or downstream (roadmap D5).

#![no_std]

/// One editor completion for a shader builtin.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CompletionEntry {
    /// GLSL-facing callable name (what the user types), e.g. `"lpfn_fbm"`, `"sin"`.
    pub name: &'static str,
    /// Builtin module the entry comes from: `"lpfn"`, `"glsl"`, or `"texture"`.
    pub module: &'static str,
    /// Display signature. LPFN entries carry the full typed GLSL signature
    /// (e.g. `"float lpfn_fbm(vec2 p, int octaves, uint seed)"`); other
    /// modules list the callable with argument names only (e.g. `"mix(x, y, a)"`).
    pub detail: &'static str,
    /// CodeMirror `snippet()` template, e.g. `"lpfn_fbm(${p}, ${octaves}, ${seed})"`.
    pub snippet: &'static str,
    /// Human description (LPFN only, from the builtin's doc comment; empty otherwise).
    pub description: &'static str,
}

/// All builtin completions, sorted by `(name, module, detail)`.
pub const COMPLETIONS: &[CompletionEntry] = &[
"#;

/// LPFN entries: one per distinct GLSL signature (matching the overload arms in
/// `glsl_lpfn_q32_builtin_id`), with typed detail, named-placeholder snippet,
/// and doc-comment description.
fn lpfn_entries(parsed: &[ParsedLpfnFunction]) -> Vec<Entry> {
    let mut entries = Vec::new();
    let grouped = group_functions_by_name(parsed);
    let mut sorted_names: Vec<&String> = grouped.keys().collect();
    sorted_names.sort();
    for glsl_name in sorted_names {
        let funcs = &grouped[glsl_name];
        let mut sigs = group_by_signature(funcs);
        sigs.sort_by(|(_, sig_a), (_, sig_b)| {
            let r = format!("{:?}", sig_a.return_type).cmp(&format!("{:?}", sig_b.return_type));
            if r != std::cmp::Ordering::Equal {
                return r;
            }
            let c = sig_a.parameters.len().cmp(&sig_b.parameters.len());
            if c != std::cmp::Ordering::Equal {
                return c;
            }
            for (pa, pb) in sig_a.parameters.iter().zip(sig_b.parameters.iter()) {
                let p = format!("{:?}{:?}", pa.ty, pa.qualifier)
                    .cmp(&format!("{:?}{:?}", pb.ty, pb.qualifier));
                if p != std::cmp::Ordering::Equal {
                    return p;
                }
            }
            std::cmp::Ordering::Equal
        });
        for (signature_funcs, sig) in sigs {
            // Prefer the Q32 variant as the representative (it always exists:
            // decimal builtins are validated as f32/q32 pairs; integer builtins
            // have a single variant-less implementation).
            let rep = signature_funcs
                .iter()
                .find(|f| f.attribute.variant == Some(Variant::Q32))
                .copied()
                .unwrap_or(signature_funcs[0]);
            let description = if !rep.doc_summary.is_empty() {
                rep.doc_summary.clone()
            } else {
                signature_funcs
                    .iter()
                    .map(|f| f.doc_summary.clone())
                    .find(|s| !s.is_empty())
                    .unwrap_or_default()
            };
            let placeholders: Vec<String> = sig
                .parameters
                .iter()
                .enumerate()
                .map(|(i, p)| {
                    if p.name.is_empty() {
                        format!("${{arg{}}}", i + 1)
                    } else {
                        format!("${{{}}}", p.name)
                    }
                })
                .collect();
            entries.push(Entry {
                name: sig.name.clone(),
                module: "lpfn",
                detail: rep.attribute.glsl_signature.trim().to_string(),
                snippet: format!("{}({})", sig.name, placeholders.join(", ")),
                description,
            });
        }
    }
    entries
}

/// glsl-import / texture entries mirroring the `(name, arg_count)`
/// mapping-table keys: name + arity snippets with the Rust parameter names as
/// placeholders (no hand-authored type detail). `lpir` and `vm` builtins are
/// IR/VM internals — not callable from user GLSL, so no entries.
fn table_entries(builtins: &[BuiltinInfo]) -> Vec<Entry> {
    let mut entries = Vec::new();
    for builtin in builtins {
        match builtin.builtin_module.as_str() {
            "glsl" => {
                for (name, count) in q32_glsl_import_keys(builtin) {
                    if name.is_empty() {
                        continue;
                    }
                    entries.push(arity_entry(&name, "glsl", &builtin.param_names, count));
                }
            }
            "texture" => {
                entries.push(arity_entry(
                    &builtin.builtin_fn_name,
                    "texture",
                    user_visible_names(builtin),
                    builtin.user_visible_param_count,
                ));
            }
            // lpfn is covered by `lpfn_entries` (typed overloads); lpir/vm
            // are internals.
            _ => {}
        }
    }
    entries
}

/// Entries for the builtins the frontend inlines (mix/clamp/dot/… — no
/// `BuiltinId`), from the compiler's own inventory
/// ([`lps_glsl::builtin_inventory::INLINED_BUILTINS`]).
fn inlined_entries() -> Vec<Entry> {
    lps_glsl::builtin_inventory::INLINED_BUILTINS
        .iter()
        .map(|builtin| {
            let names: Vec<String> = builtin.params.iter().map(|p| String::from(*p)).collect();
            arity_entry(builtin.name, "glsl", &names, names.len())
        })
        .collect()
}

/// User-visible parameter names (drops the implicit `VmContext` first param).
fn user_visible_names(builtin: &BuiltinInfo) -> &[String] {
    if builtin.needs_vmctx && !builtin.param_names.is_empty() {
        &builtin.param_names[1..]
    } else {
        &builtin.param_names
    }
}

/// Build a name+arity entry (`detail` and `snippet` use the given parameter names,
/// falling back to `argN` if the count does not line up).
fn arity_entry(name: &str, module: &'static str, param_names: &[String], arity: usize) -> Entry {
    let names: Vec<String> = if param_names.len() == arity {
        param_names.to_vec()
    } else {
        (1..=arity).map(|i| format!("arg{i}")).collect()
    };
    let placeholders: Vec<String> = names.iter().map(|n| format!("${{{n}}}")).collect();
    Entry {
        name: name.to_string(),
        module,
        detail: format!("{}({})", name, names.join(", ")),
        snippet: format!("{}({})", name, placeholders.join(", ")),
        description: String::new(),
    }
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
