[target.'cfg(target_arch = "riscv32")']
rustflags = [
  "-C", "target-feature=-c",
  "-C", "force-frame-pointers",
  "-C", "force-unwind-tables=yes",
  "-C", "panic=unwind",
]

[unstable]
build-std = ["core", "alloc"]
