kind = "Project"
name = "fast"

[nodes.output]
ref = "./output.toml"

[nodes.clock]
ref = "./clock.toml"

[nodes.texture]
ref = "./texture.toml"

[nodes.shader]
ref = "./shader.toml"

[nodes.fixture]
ref = "./fixture.toml"
