use std::env;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=src");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let src_dir = manifest_dir.join("src");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("out dir"));
    let generated_path = out_dir.join("story_registry.generated.rs");

    let mut story_files = Vec::new();
    collect_story_files(&src_dir, &mut story_files).expect("scan story files");
    story_files.sort();

    let mut generated = String::new();
    generated.push_str("// @generated by lpa-studio-web/build.rs\n\n");

    for (index, story_file) in story_files.iter().enumerate() {
        let module_name = story_module_name(&src_dir, story_file, index);
        generated.push_str("#[path = \"");
        generated.push_str(&rust_string_literal_path(story_file));
        generated.push_str("\"]\n");
        generated.push_str("mod ");
        generated.push_str(&module_name);
        generated.push_str(";\n");
    }

    generated.push_str(
        "\npub fn all_generated_stories() -> Vec<crate::stories::story::StoryDescriptor> {\n",
    );
    generated.push_str("    let mut stories = Vec::new();\n");
    for (index, story_file) in story_files.iter().enumerate() {
        let module_name = story_module_name(&src_dir, story_file, index);
        generated.push_str("    stories.extend(");
        generated.push_str(&module_name);
        generated.push_str("::stories());\n");
    }
    generated.push_str("    stories\n");
    generated.push_str("}\n");

    generated.push_str(
        "\npub fn render_generated_story(id: &str) -> Option<dioxus::prelude::Element> {\n",
    );
    for (index, story_file) in story_files.iter().enumerate() {
        let module_name = story_module_name(&src_dir, story_file, index);
        generated.push_str("    if let Some(element) = ");
        generated.push_str(&module_name);
        generated.push_str("::render_story(id) {\n");
        generated.push_str("        return Some(element);\n");
        generated.push_str("    }\n");
    }
    generated.push_str("    None\n");
    generated.push_str("}\n");

    fs::write(generated_path, generated).expect("write generated story registry");
}

fn collect_story_files(dir: &Path, story_files: &mut Vec<PathBuf>) -> io::Result<()> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_story_files(&path, story_files)?;
            continue;
        }

        let Some(file_name) = path.file_name().and_then(|file_name| file_name.to_str()) else {
            continue;
        };
        if file_name.ends_with("_story.rs") {
            story_files.push(path);
        }
    }
    Ok(())
}

fn story_module_name(src_dir: &Path, story_file: &Path, index: usize) -> String {
    let relative = story_file
        .strip_prefix(src_dir)
        .expect("story file under src");
    let mut name = format!("story_{index}");
    for component in relative.components() {
        name.push('_');
        let segment = component.as_os_str().to_string_lossy();
        for ch in segment.chars() {
            if ch.is_ascii_alphanumeric() {
                name.push(ch.to_ascii_lowercase());
            } else {
                name.push('_');
            }
        }
    }
    name
}

fn rust_string_literal_path(path: &Path) -> String {
    path.to_string_lossy()
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
}
