kind = "Output"
endpoint = "ws281x:rmt:D4"

[bindings.input]
source = "bus#control.out"

[options]
white_point = [0.9, 1.0, 1.0]
brightness = 0.12
interpolation_enabled = true
dithering_enabled = false
lut_enabled = true
