kind = "Project"
name = "basic"

[nodes.output]
artifact = "./output.toml"

[nodes.clock]
artifact = "./clock.toml"

[nodes.shader]
artifact = "./shader.toml"

[nodes.fixture]
artifact = "./fixture.toml"
