kind = "Project"
name = "basic"

[nodes.output]
def = { path = "./output.toml" }

[nodes.clock]
def = { path = "./clock.toml" }

[nodes.shader]
def = { path = "./shader.toml" }

[nodes.fixture]
def = { path = "./fixture.toml" }
