//! GLSL name → `BuiltinId` for Q32 WASM imports.
//!
//! AUTO-GENERATED by lp-glsl-builtins-gen-app. Do not edit manually.
//!
//! - `glsl_q32_math_builtin_id`: standard math libcalls (`sin`, `atan`, …).
//! - `glsl_lpfx_q32_builtin_id`: `lpfx_*` overloads keyed by parameter types.
//!
//! Regenerate: `cargo run -p lp-glsl-builtins-gen-app` or `scripts/build-builtins.sh`

use super::BuiltinId;

/// Parameter types for LPFX overload resolution (matches GLSL, not flattened WASM).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum GlslParamKind {
    Bool,
    Int,
    UInt,
    Float,
    Vec2,
    Vec3,
    Vec4,
    IVec2,
    IVec3,
    IVec4,
    UVec2,
    UVec3,
    UVec4,
    BVec2,
    BVec3,
    BVec4,
}

/// Map GLSL math name + **AST argument count** to a scalar `__lp_q32_*` import.
/// Returns `None` for builtins implemented inline in WASM (e.g. `clamp`) or unknown names.
pub fn glsl_q32_math_builtin_id(name: &str, arg_count: usize) -> Option<BuiltinId> {
    match (name, arg_count) {
        ("acos", 1) => Some(BuiltinId::LpQ32Acos),
        ("acosh", 1) => Some(BuiltinId::LpQ32Acosh),
        ("add", 2) => Some(BuiltinId::LpQ32Add),
        ("asin", 1) => Some(BuiltinId::LpQ32Asin),
        ("asinh", 1) => Some(BuiltinId::LpQ32Asinh),
        ("atan", 1) => Some(BuiltinId::LpQ32Atan),
        ("atan", 2) => Some(BuiltinId::LpQ32Atan2),
        ("atanh", 1) => Some(BuiltinId::LpQ32Atanh),
        ("cos", 1) => Some(BuiltinId::LpQ32Cos),
        ("cosh", 1) => Some(BuiltinId::LpQ32Cosh),
        ("div", 2) => Some(BuiltinId::LpQ32Div),
        ("exp", 1) => Some(BuiltinId::LpQ32Exp),
        ("exp2", 1) => Some(BuiltinId::LpQ32Exp2),
        ("fma", 3) => Some(BuiltinId::LpQ32Fma),
        ("inversesqrt", 1) => Some(BuiltinId::LpQ32Inversesqrt),
        ("ldexp", 2) => Some(BuiltinId::LpQ32Ldexp),
        ("log", 1) => Some(BuiltinId::LpQ32Log),
        ("log2", 1) => Some(BuiltinId::LpQ32Log2),
        ("mod", 2) => Some(BuiltinId::LpQ32Mod),
        ("mul", 2) => Some(BuiltinId::LpQ32Mul),
        ("pow", 2) => Some(BuiltinId::LpQ32Pow),
        ("round", 1) => Some(BuiltinId::LpQ32Round),
        ("roundEven", 1) => Some(BuiltinId::LpQ32Roundeven),
        ("sin", 1) => Some(BuiltinId::LpQ32Sin),
        ("sinh", 1) => Some(BuiltinId::LpQ32Sinh),
        ("sqrt", 1) => Some(BuiltinId::LpQ32Sqrt),
        ("sub", 2) => Some(BuiltinId::LpQ32Sub),
        ("tan", 1) => Some(BuiltinId::LpQ32Tan),
        ("tanh", 1) => Some(BuiltinId::LpQ32Tanh),
        _ => None,
    }
}

/// Map `lpfx_*` name + parameter type list to the Q32 `BuiltinId`.
pub fn glsl_lpfx_q32_builtin_id(name: &str, params: &[GlslParamKind]) -> Option<BuiltinId> {
    match (name, params) {
        ("lpfx_fbm", &[GlslParamKind::Vec2, GlslParamKind::Int, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpfxFbm2Q32)
        }
        (
            "lpfx_fbm",
            &[
                GlslParamKind::Vec3,
                GlslParamKind::Float,
                GlslParamKind::Int,
                GlslParamKind::UInt,
            ],
        ) => Some(BuiltinId::LpfxFbm3TileQ32),
        ("lpfx_fbm", &[GlslParamKind::Vec3, GlslParamKind::Int, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpfxFbm3Q32)
        }
        ("lpfx_gnoise", &[GlslParamKind::Float, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpfxGnoise1Q32)
        }
        ("lpfx_gnoise", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpfxGnoise2Q32)
        }
        (
            "lpfx_gnoise",
            &[
                GlslParamKind::Vec3,
                GlslParamKind::Float,
                GlslParamKind::UInt,
            ],
        ) => Some(BuiltinId::LpfxGnoise3TileQ32),
        ("lpfx_gnoise", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpfxGnoise3Q32)
        }
        ("lpfx_hash", &[GlslParamKind::UInt, GlslParamKind::UInt]) => Some(BuiltinId::LpfxHash1),
        ("lpfx_hash", &[GlslParamKind::UVec2, GlslParamKind::UInt]) => Some(BuiltinId::LpfxHash2),
        ("lpfx_hash", &[GlslParamKind::UVec3, GlslParamKind::UInt]) => Some(BuiltinId::LpfxHash3),
        ("lpfx_hsv2rgb", &[GlslParamKind::Vec3]) => Some(BuiltinId::LpfxHsv2rgbQ32),
        ("lpfx_hsv2rgb", &[GlslParamKind::Vec4]) => Some(BuiltinId::LpfxHsv2rgbVec4Q32),
        ("lpfx_hue2rgb", &[GlslParamKind::Float]) => Some(BuiltinId::LpfxHue2rgbQ32),
        (
            "lpfx_psrdnoise",
            &[
                GlslParamKind::Vec2,
                GlslParamKind::Vec2,
                GlslParamKind::Float,
                GlslParamKind::Vec2,
                GlslParamKind::UInt,
            ],
        ) => Some(BuiltinId::LpfxPsrdnoise2Q32),
        (
            "lpfx_psrdnoise",
            &[
                GlslParamKind::Vec3,
                GlslParamKind::Vec3,
                GlslParamKind::Float,
                GlslParamKind::Vec3,
                GlslParamKind::UInt,
            ],
        ) => Some(BuiltinId::LpfxPsrdnoise3Q32),
        ("lpfx_random", &[GlslParamKind::Float, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpfxRandom1Q32)
        }
        ("lpfx_random", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpfxRandom2Q32)
        }
        ("lpfx_random", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpfxRandom3Q32)
        }
        ("lpfx_rgb2hsv", &[GlslParamKind::Vec3]) => Some(BuiltinId::LpfxRgb2hsvQ32),
        ("lpfx_rgb2hsv", &[GlslParamKind::Vec4]) => Some(BuiltinId::LpfxRgb2hsvVec4Q32),
        ("lpfx_saturate", &[GlslParamKind::Float]) => Some(BuiltinId::LpfxSaturateQ32),
        ("lpfx_saturate", &[GlslParamKind::Vec3]) => Some(BuiltinId::LpfxSaturateVec3Q32),
        ("lpfx_saturate", &[GlslParamKind::Vec4]) => Some(BuiltinId::LpfxSaturateVec4Q32),
        ("lpfx_snoise", &[GlslParamKind::Float, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpfxSnoise1Q32)
        }
        ("lpfx_snoise", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpfxSnoise2Q32)
        }
        ("lpfx_snoise", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpfxSnoise3Q32)
        }
        ("lpfx_srandom", &[GlslParamKind::Float, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpfxSrandom1Q32)
        }
        ("lpfx_srandom", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpfxSrandom2Q32)
        }
        ("lpfx_srandom", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpfxSrandom3Q32)
        }
        (
            "lpfx_srandom3_tile",
            &[
                GlslParamKind::Vec3,
                GlslParamKind::Float,
                GlslParamKind::UInt,
            ],
        ) => Some(BuiltinId::LpfxSrandom3TileQ32),
        ("lpfx_srandom3_vec", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpfxSrandom3VecQ32)
        }
        ("lpfx_worley", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpfxWorley2Q32)
        }
        ("lpfx_worley", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpfxWorley3Q32)
        }
        ("lpfx_worley_value", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpfxWorley2ValueQ32)
        }
        ("lpfx_worley_value", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpfxWorley3ValueQ32)
        }
        _ => None,
    }
}

#[cfg(test)]
mod glsl_builtin_mapping_tests {
    use super::{GlslParamKind, glsl_lpfx_q32_builtin_id, glsl_q32_math_builtin_id};
    use crate::BuiltinId;

    #[test]
    fn q32_sin() {
        assert_eq!(
            glsl_q32_math_builtin_id("sin", 1),
            Some(BuiltinId::LpQ32Sin)
        );
    }

    #[test]
    fn q32_atan_two_args_is_atan2_import() {
        assert_eq!(
            glsl_q32_math_builtin_id("atan", 2),
            Some(BuiltinId::LpQ32Atan2)
        );
    }

    #[test]
    fn lpfx_fbm_vec2() {
        assert_eq!(
            glsl_lpfx_q32_builtin_id(
                "lpfx_fbm",
                &[GlslParamKind::Vec2, GlslParamKind::Int, GlslParamKind::UInt],
            ),
            Some(BuiltinId::LpfxFbm2Q32)
        );
    }
}
